Access most comprehensive table saved and add questionnaire data and scores

In [22]:
import sys
import os

sys.path.append('/Users/benny/Repos/octagon_analysis')

In [24]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import parse_data.prepare_data as prepare_data
import parse_data.identify_filepaths as identify_filepaths
import trait_analyses.functions.prepare_questionnaire_data as prepare_questionnaire_data
import globals

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
data_folder = '/Volumes/ogma/human_octagon/RAW/standard'
#personal_data_csv = '/Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/questionnaire_data/personal_data.csv'

In [15]:
social_files, ordered_solos = identify_filepaths.get_filenames(data_folder=data_folder)

In [16]:
first_solos = ordered_solos[::2]
second_solos = ordered_solos[1::2]

In [17]:
first_solos

['240913_1/2024-09-13_11-23-37_YW13_FirstSolo.json',
 '240913_1/2024-09-13_11-23-50_JL13_FirstSolo.json',
 '240927_1/2024-09-27_14-14-31_SH27_FirstSolo.json',
 '240927_1/2024-09-27_14-14-42_EN27_FirstSolo.json',
 '241017_1/2024-10-17_14-20-28_SP17_FirstSolo.json',
 '241017_1/2024-10-17_14-20-50_AW17_FirstSolo.json',
 '241017_2/2024-10-17_16-36-0_ZH17_FirstSolo.json',
 '241017_2/2024-10-17_16-35-45_EM17_FirstSolo.json',
 '241112_1/2024-11-12_13-19-22_KA12_FirstSolo.json',
 '241112_1/2024-11-12_13-18-59_WM12_FirstSolo.json',
 '241112_2/2024-11-12_15-13-34_FA12_FirstSolo.json',
 '241112_2/2024-11-12_15-11-45_SL12_FirstSolo.json',
 '241113_1/2024-11-13_14-12-43_NK13_FirstSolo.json',
 '241113_1/2024-11-13_14-12-41_RD13_FirstSolo.json',
 '241113_2/2024-11-13_15-22-20_YL13_FirstSolo.json',
 '241113_2/2024-11-13_15-21-50_HC13_FirstSolo.json',
 '241119_1/2024-11-19_14-18-18_AV19_FirstSolo.json',
 '241119_1/2024-11-19_14-18-44_XG19_FirstSolo.json',
 '241119_2/2024-11-19_15-15-53_SB19_FirstSolo.json',
 '241119_2/2024-11-19_15-14-19_HH19_FirstSolo.json',
 '241120_1/2024-11-20_14-12-06_JS20_FirstSolo.json',
 '241120_1/2024-11-20_14-12-33_RR20_FirstSolo.json',
 '241120_2/2024-11-20_15-10-00_ZS20_FirstSolo.json',
 '241120_2/2024-11-20_15-10-17_VC20_FirstSolo.json',
 '241203_1/2024-12-03_14-20-13_PO03_FirstSolo.json',
 '241203_1/2024-12-03_14-19-21_NN03_FirstSolo.json',
 '241203_2/2024-12-03_15-19-51_EX03_FirstSolo.json',
 '241203_2/2024-12-03_15-20-09_BC03_FirstSolo.json',
 '241210_1/2024-12-10_14-13-47_TE10_FirstSolo.json',
 '241210_1/2024-12-10_14-12-58_TK10_FirstSolo.json',
 '241210_2/2024-12-10_15-12-18_RK10_FirstSolo.json',
 '241210_2/2024-12-10_15-11-46_RU10_FirstSolo.json',
 '241219_1/2024-12-19_15-20-18_JU19_FirstSolo.json',
 '241219_1/2024-12-19_15-22-13_SY19_FirstSolo.json',
 '241220_1/2024-12-20_17-36-27_KS20_FirstSolo.json',
 '241220_1/2024-12-20_17-36-54_CS20_FirstSolo.json',
 '250115_1/2025-01-15_15-12-13_YY15_FirstSolo.json',
 '250115_1/2025-01-15_15-12-39_MR15_FirstSolo.json',
 '250115_2/2025-01-15_16-14-40_YL15_FirstSolo.json',
 '250115_2/2025-01-15_16-14-58_RR15_FirstSolo.json',
 '250204_2/2025-02-04_16-58-53_DB04_FirstSolo.json',
 '250204_2/2025-02-04_16-58-37_GG04_FirstSolo.json',
 '250314_1/2025-03-14_12-03-08_KC14_FirstSolo.json',
 '250314_1/2025-03-14_12-03-22_WL14_FirstSolo.json',
 '250314_2/2025-03-14_12-59-24_AE14_FirstSolo.json',
 '250314_2/2025-03-14_12-59-36_JL14_FirstSolo.json',
 '250314_3/2025-03-14_14-12-29_MA14_FirstSolo.json',
 '250314_3/2025-03-14_14-12-49_RM14_FirstSolo.json',
 '250318_1/2025-03-18_14-09-51_SJ18_FirstSolo.json',
 '250318_1/2025-03-18_14-10-34_CD18_FirstSolo.json',
 '250318_2/2025-03-18_16-10-59_JK18_FirstSolo.json',
 '250318_2/2025-03-18_16-11-11_HL18_FirstSolo.json',
 '250318_3/2025-03-18_17-15-58_HM18_FirstSolo.json',
 '250318_3/2025-03-18_17-16-10_SC18_FirstSolo.json',
 '250319_1/2025-03-19_13-17-55_HL19_FirstSolo.json',
 '250319_1/2025-03-19_13-17-46_AW19_FirstSolo.json',
 '250319_2/2025-03-19_14-22-02_PT19_FirstSolo.json',
 '250319_2/2025-03-19_14-22-13_JL19_FirstSolo.json',
 '250401_1/2025-04-01_14-15-29_IS01_FirstSolo.json',
 '250401_1/2025-04-01_14-15-24_HQ01_FirstSolo.json',
 '250401_2/2025-04-01_15-17-03_AL01_FirstSolo.json',
 '250401_2/2025-04-01_15-17-26_NL01_FirstSolo.json',
 '250402_1/2025-04-02_16-13-59_SH02_FirstSolo.json',
 '250402_1/2025-04-02_16-14-13_ML02_FirstSolo.json',
 '250404_1/2025-04-04_10-18-59_JW04_FirstSolo.json',
 '250404_1/2025-04-04_10-19-11_JI04_FirstSolo.json',
 '250410_1/2025-04-10_12-16-12_AR10_FirstSolo.json',
 '250410_1/2025-04-10_12-16-26_MY10_FirstSolo.json',
 '250411_1/2025-04-11_09-17-58_IN11_FirstSolo.json',
 '250411_1/2025-04-11_09-18-11_CW11_FirstSolo.json',
 '250417_1/2025-04-17_12-09-51_CY17_FirstSolo.json',
 '250417_1/2025-04-17_12-10-56_RL17_FirstSolo.json',
 '250421_1/2025-04-21_09-18-28_NM21_FirstSolo.json',
 '250421_1/2025-04-21_09-18-42_KC21_FirstSolo.json',
 '250421_2/2025-04-21_10-18-48_LM21_FirstSolo.json',
 '250421_2/2025-04-21_10-18-58_LS21_FirstSolo.json',
 '250502_1/2025-05-02_11-09-55_JC02_FirstSolo.json',
 '250502_1/2025-05-02_11-10-14_KS02_FirstSolo.json',
 '250509_1/2025-05-09_12-18-03_AM09_FirstSolo.json',
 '250509_1/2025-05-09_12-18-53_MC09_FirstSolo.json',
 '250512_1/2025-05-12_09-24-24_TG12_FirstSolo.json',
 '250512_1/2025-05-12_09-24-39_SC12_FirstSolo.json',
 '250512_2/2025-05-12_12-10-42_NO12_FirstSolo.json',
 '250512_2/2025-05-12_12-10-18_AS12_FirstSolo.json',
 '250520_1/2025-05-20_14-15-25_CY20_FirstSolo.json',
 '250520_1/2025-05-20_14-15-00_MJ20_FirstSolo.json',
 '250521_1/2025-05-21_09-21-15_EH21_FirstSolo.json',
 '250521_1/2025-05-21_09-21-16_SP21_FirstSolo.json',
 '250522_1/2025-05-22_09-15-24_SS22_FirstSolo.json',
 '250522_1/2025-05-22_09-15-49_AD22_FirstSolo.json',
 '250523_1/2025-05-23_17-54-31_JW23_FirstSolo.json',
 '250523_1/2025-05-23_17-54-43_YL23_FirstSolo.json',
 '250524_1/2025-05-24_10-16-54_JP24_FirstSolo.json',
 '250524_1/2025-05-24_10-17-04_IP24_FirstSolo.json',
 '250530_1/2025-05-30_11-18-37_ZZ30_FirstSolo.json',
 '250530_1/2025-05-30_11-18-19_VW30_FirstSolo.json',
 '250604_1/2025-06-04_15-11-03_MP04_FirstSolo.json',
 '250604_1/2025-06-04_15-11-26_SH04_FirstSolo.json',
 '250620_1/2025-06-20_15-18-58_JK20_FirstSolo.json',
 '250620_1/2025-06-20_15-19-07_DD20_FirstSolo.json',
 '251003_1/2025-10-03_12-15-34_SI03_FirstSolo.json',
 '251003_1/2025-10-03_12-14-36_YL03_FirstSolo.json',
 '251010_1/2025-10-10_10-08-29_AP10_FirstSolo.json',
 '251010_1/2025-10-10_10-08-13_CZ10_FirstSolo.json',
 '251010_2/2025-10-10_11-15-39_ES10_FirstSolo.json',
 '251010_2/2025-10-10_11-15-28_NM10_FirstSolo.json',
 '251010_3/2025-10-10_14-28-00_HT10_FirstSolo.json',
 '251010_3/2025-10-10_14-27-52_WT10_FirstSolo.json',
 '251010_4/2025-10-10_15-28-22_YL10_FirstSolo.json',
 '251010_4/2025-10-10_15-28-37_NO10_FirstSolo.json',
 '251013_1/2025-10-13_13-13-04_FA13_FirstSolo.json',
 '251013_1/2025-10-13_13-12-53_SW13_FirstSolo.json',
 '251013_2/2025-10-13_14-16-45_SW13_FirstSolo.json',
 '251013_2/2025-10-13_14-16-36_MU13_FirstSolo.json',
 '251015_1/2025-10-15_09-10-38_CS15_FirstSolo.json',
 '251015_1/2025-10-15_09-10-52_SK15_FirstSolo.json',
 '251017_1/2025-10-17_10-16-46_XL17_FirstSolo.json',
 '251017_1/2025-10-17_10-17-01_EV17_FirstSolo.json',
 '251017_2/2025-10-17_11-18-32_MZ17_FirstSolo.json',
 '251017_2/2025-10-17_11-18-44_CW17_FirstSolo.json',
 '251103_1/2025-11-03_13-18-16_TG03_FirstSolo.json',
 '251103_1/2025-11-03_13-17-59_HW03_FirstSolo.json',
 '251103_2/2025-11-03_16-13-23_YG03_FirstSolo.json',
 '251103_2/2025-11-03_16-13-02_XA03_FirstSolo.json',
 '251104_1/2025-11-04_13-18-40_YL04_FirstSolo.json',
 '251104_1/2025-11-04_13-18-58_MV04_FirstSolo.json',
 '251105_1/2025-11-05_14-16-53_ZO05_FirstSolo.json',
 '251105_1/2025-11-05_14-16-20_CL05_FirstSolo.json',
 '251120_1/2025-11-20_10-21-38_NH20_FirstSolo.json',
 '251120_1/2025-11-20_10-21-21_MA20_FirstSolo.json',
 '251215_1/2025-12-15_11-22-45_CK15_FirstSolo.json',
 '251215_1/2025-12-15_11-23-02_AM15_FirstSolo.json',
 '251219_1/2025-12-19_12-55-14_PE19_FirstSolo.json',
 '251219_1/2025-12-19_12-54-54_AT19_FirstSolo.json',
 '251219_2/2025-12-19_13-53-59_NJ19_FirstSolo.json',
 '251219_2/2025-12-19_13-54-13_BL19_FirstSolo.json',
 '260107_1/2026-01-07_10-17-45_AF07_FirstSolo.json',
 '260107_1/2026-01-07_10-17-37_AC07_FirstSolo.json',
 '260109_1/2026-01-09_10-17-52_AM09_FirstSolo.json',
 '260109_1/2026-01-09_10-18-05_FB09_FirstSolo.json',
 '260109_2/2026-01-09_11-20-42_IM09_FirstSolo.json',
 '260109_2/2026-01-09_11-20-34_KM09_FirstSolo.json',
 '260114_1/2026-01-14_13-42-41_CG14_FirstSolo.json',
 '260114_1/2026-01-14_13-43-11_JD14_FirstSolo.json',
 '260116_1/2026-01-16_14-19-35_EL16_FirstSolo.json',
 '260116_1/2026-01-16_14-20-00_FR16_FirstSolo.json',
 '260120_1/2026-01-20_12-21-29_RA20_FirstSolo.json',
 '260120_1/2026-01-20_12-21-42_AM20_FirstSolo.json',
 '260120_2/2026-01-20_13-24-01_LW20_FirstSolo.json',
 '260120_2/2026-01-20_13-24-10_SG20_FirstSolo.json',
 '260120_3/2026-01-20_14-26-50_HH20_FirstSolo.json',
 '260120_3/2026-01-20_14-26-59_KH20_FirstSolo.json',
 '260121_1/2026-01-21_13-14-42_ZC21_FirstSolo.json',
 '260121_1/2026-01-21_13-14-57_JX21_FirstSolo.json',
 '260128_1/2026-01-28_12-23-38_OK28_FirstSolo.json',
 '260128_1/2026-01-28_12-25-47_DP28_FirstSolo.json',
 '260128_2/2026-01-28_13-26-00_YG28_FirstSolo.json',
 '260128_2/2026-01-28_13-25-50_GN28_FirstSolo.json',
 '260130_1/2026-01-30_17-16-35_ZT30_FirstSolo.json',
 '260130_1/2026-01-30_17-16-07_SW30_FirstSolo.json',
 '260202_1/2026-02-02_13-10-03_KF02_FirstSolo.json',
 '260202_1/2026-02-02_13-10-26_KS02_FirstSolo.json',
 '260204_1/2026-02-04_13-21-13_YL04_FirstSolo.json',
 '260204_1/2026-02-04_13-21-43_LY04_FirstSolo.json',
 '260205_1/2026-02-05_13-17-46_MO05_FirstSolo.json',
 '260205_1/2026-02-05_13-18-03_IP05_FirstSolo.json',
 '260209_1/2026-02-09_17-09-55_KW09_FirstSolo.json',
 '260209_1/2026-02-09_17-09-44_BR09_FirstSolo.json',
 '260209_2/2026-02-09_18-13-23_YS09_FirstSolo.json',
 '260209_2/2026-02-09_18-13-33_ZX09_FirstSolo.json',
 '260213_1/2026-02-13_13-11-07_NA13_FirstSolo.json',
 '260213_1/2026-02-13_13-11-17_EK13_FirstSolo.json',
 '260216_1/2026-02-16_09-20-00_MP16_FirstSolo.json',
 '260216_1/2026-02-16_09-19-49_JS16_FirstSolo.json',
 '260218_1/2026-02-18_17-14-24_AJ18_FirstSolo.json',
 '260218_1/2026-02-18_17-14-38_LZ18_FirstSolo.json',
 '260219_1/2026-02-19_14-40-33_NB19_FirstSolo.json',
 '260219_1/2026-02-19_14-40-21_AS19_FirstSolo.json',
 '260220_1/2026-02-20_11-15-38_SS20_FirstSolo.json',
 '260220_1/2026-02-20_11-15-49_YL20_FirstSolo.json',
 '260220_2/2026-02-20_16-16-43_KR20_FirstSolo.json',
 '260220_2/2026-02-20_16-16-30_PJ20_FirstSolo.json',
 '260304_1/2026-03-04_13-08-35_RL04_FirstSolo.json',
 '260304_1/2026-03-04_13-08-23_AK04_FirstSolo.json',
 '260306_1/2026-03-06_13-25-07_AT06_FirstSolo.json',
 '260306_1/2026-03-06_13-25-17_AK06_FirstSolo.json',
 '260306_2/2026-03-06_15-10-39_ZB06_FirstSolo.json',
 '260306_2/2026-03-06_15-10-49_LS06_FirstSolo.json',
 '260309_1/2026-03-09_14-17-01_NC09_FirstSolo.json',
 '260309_1/2026-03-09_14-17-17_EE09_FirstSolo.json',
 '260317_1/2026-03-17_15-13-52_AS17_FirstSolo.json',
 '260317_1/2026-03-17_15-14-05_QC17_FirstSolo.json',
 '260319_1/2026-03-19_11-48-04_JP19_FirstSolo.json',
 '260319_1/2026-03-19_11-47-54_LM19_FirstSolo.json',
 '260323_1/2026-03-23_11-17-48_SL23_FirstSolo.json',
 '260323_1/2026-03-23_11-17-37_KF23_FirstSolo.json',
 '260327_1/2026-03-27_11-09-47_MI27_FirstSolo.json',
 '260327_1/2026-03-27_11-09-34_YZ27_FirstSolo.json',
 '260327_2/2026-03-27_14-15-06_DT27_FirstSolo.json',
 '260327_2/2026-03-27_14-15-19_RW27_FirstSolo.json',
 '260330_1/2026-03-30_15-21-31_JJ30_FirstSolo.json',
 '260330_1/2026-03-30_15-21-21_NC30_FirstSolo.json']

In [18]:
AQ_path='/Users/benny/Desktop/questionnaire_responses/AQ.csv'
BIS_path='/Users/benny/Desktop/questionnaire_responses/BIS.csv'
GAD_path='/Users/benny/Desktop/questionnaire_responses/GAD.csv'

In [25]:
questionnaire_data_df = prepare_questionnaire_data.preprocess_data(AQ_path, GAD_path, BIS_path)

/Users/benny/Desktop/questionnaire_responses/AQ.csv
/Users/benny/Desktop/questionnaire_responses/GAD.csv
/Users/benny/Desktop/questionnaire_responses/BIS.csv

In [26]:
questionnaire_data_df

          date pseudonym  GAD_total  AQ_total  BIS_total
0   2026-03-06      AK06         15         6         21
3   2026-02-18      AJ18          7         2         14
4   2024-10-17      AW17          5         9         11
6   2025-12-19      AT19          5         2         14
7   2026-01-09      AM09          7         6         28
..         ...       ...        ...       ...        ...
280 2026-01-30      ZT30          8         2         22
281 2025-05-30      ZZ30          2         8         13
282 2026-01-21      ZC21          8         3         17
283 2025-10-17      ZH17          5         9         21
284 2024-11-20      ZS20          2         4         17

[194 rows x 5 columns]

In [7]:
import re
pseudo_tuples_list = []
experiment_dates_socials = []
for file in social_files:
     # match the session number and the pseudonym string
    match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?_.*?)_Social\.json', file)
    if match:
        session, date, time, pseudonyms = match.groups()
        pseudo_tuples = pseudonyms.split('_')[0::]
        pseudo_tuples_list.append(pseudo_tuples)
        experiment_dates_socials.append(date)

In [8]:
opponent_dict = {}

for i, pseudonym in enumerate(pseudo_tuples_list):
    player0 = pseudonym[0]
    player1 = pseudonym[1]

    if player0 not in opponent_dict:
        opponent_dict[player0] = []
    if player1 not in opponent_dict:
        opponent_dict[player1] = []

    opponent_dict[player0] = player1
    opponent_dict[player1] = player0

In [41]:
df = pd.read_csv('individual_analyses_table_7.csv', index_col=0)

In [33]:
df_2 = pd.read_csv('individual_analyses_table_8.csv', index_col=0)

In [34]:
df['rt_by_traj_efficiency_first_solo'] = df_2['rt_by_traj_efficiency_first_solo']
df['rt_by_traj_efficiency_second_solo'] = df_2['rt_by_traj_efficiency_second_solo']
df['rt_by_traj_efficiency_combined_solo'] = df_2['rt_by_traj_efficiency_combined_solo']
df['rt_combined_solos'] = df_2['rt_combined_solos']
df['traj_efficiency_combined_solos'] = df_2['traj_efficiency_combined_solos']
df['rt_by_traj_efficiency_wins'] = df_2['rt_by_traj_efficiency_wins']
df['rt_by_traj_efficiency_losses'] = df_2['rt_by_traj_efficiency_losses']
df['rt_wins'] = df_2['rt_wins']
df['rt_losses'] = df_2['rt_losses']
df['traj_efficiency_wins'] = df_2['traj_efficiency_wins']
df['traj_efficiency_losses'] = df_2['traj_efficiency_losses']

In [10]:
df

,experiment_date,pH_H_first_vis_combined_solo_sep1,pH_H_first_vis_combined_solo_sep2,pH_H_first_vis_combined_solo_sep4,pH_H_first_vis_combined_solo_all_seps,pH_H_first_vis_first_solo_all_seps,pH_H_first_vis_second_solo_all_seps,pH_H_first_vis_social_sep1,pH_H_first_vis_social_sep2,pH_H_first_vis_social_sep4,pH_H_first_vis_social_all_seps,pH_L_first_vis_combined_solo_sep1,pH_L_first_vis_combined_solo_sep2,pH_L_first_vis_combined_solo_sep4,pH_L_first_vis_combined_solo_all_seps,pH_L_first_vis_first_solo_all_seps,pH_L_first_vis_second_solo_all_seps,pH_L_first_vis_social_sep1,pH_L_first_vis_social_sep2,pH_L_first_vis_social_sep4,pH_L_first_vis_social_all_seps,sensory_effect_solo_sep1,sensory_effect_social_sep1,solo-social_sensory_effect_sep1,sensory_effect_solo_sep2,sensory_effect_social_sep2,solo-social_sensory_effect_sep2,sensory_effect_solo_sep4,sensory_effect_social_sep4,solo-social_sensory_effect_sep4,sensory_effect_solo_all_seps,sensory_effect_social_all_seps,solo-social_sensory_effect_all_seps,pH_opp_visible_sep_1,pH_opp_visible_sep_2,pH_opp_visible_sep_4,pH_opp_visible_all_seps,pH_opp_not_visible_sep_1,pH_opp_not_visible_sep_2,pH_opp_not_visible_sep_4,pH_opp_not_visible_all_seps,p_win_other_visible_sep_1,p_win_other_visible_sep_2,p_win_other_visible_sep_4,p_win_other_visible,p_win_other_not_visible_sep_1,p_win_other_not_visible_sep_2,p_win_other_not_visible_sep_4,p_win_other_not_visible,solo_centre_occupancy_between_trials,solo_distance_travelled_between_trials,solo_central_tendency_at_slice_onset,solo_central_tendency_throughout_trajectory,social_centre_occupancy_between_trials,social_distance_travelled_between_trials,social_central_tendency_at_slice_onset,social_central_tendency_throughout_trajectory,rt_by_traj_efficiency_first_solo,rt_by_traj_efficiency_second_solo,rt_by_traj_efficiency_combined_solo,rt_combined_solos,traj_efficiency_combined_solos,rt_by_traj_efficiency_wins,rt_by_traj_efficiency_losses,rt_wins,rt_losses,traj_efficiency_wins,traj_efficiency_losses
TK10,2024-12-10,NaN,1.000000000,NaN,1.000000000,1.000000000,1.000000000,0.800000000,0.875000000,1.000000000,0.882352941,NaN,0.785714286,0.750000000,0.814814815,0.833333333,0.800000000,0.416666667,0.181818182,0.153846154,0.234042553,NaN,0.383333333,NaN,0.214285714,0.693181818,-0.478896104,NaN,0.846153846,NaN,0.185185185,0.648310388,-0.463125203,0.600000000,0.500000000,0.300000000,0.475000000,0.583333333,0.511111111,0.454545455,0.524271845,0.600000000,0.476190476,0.500000000,0.512195122,0.642857143,0.678571429,0.461538462,0.623188406,81.527574142,20.557037892,0.742367399,0.589442460,79.566697439,41.918692348,0.619212796,0.509680777,0.945914274,0.851731597,0.944118107,0.935539210,0.952697004,0.882218665,0.661307717,0.884800414,0.604361135,0.879636915,0.718254298
IN04,2025-02-04,0.909090909,NaN,1.000000000,0.947368421,0.909090909,1.000000000,0.875000000,NaN,NaN,0.941176471,1.000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,NaN,0.769230769,-0.090909091,-0.125000000,0.034090909,NaN,NaN,NaN,0.000000000,NaN,NaN,-0.052631579,0.171945701,-0.224577280,0.933333333,NaN,NaN,0.884615385,0.958333333,0.875000000,0.714285714,0.897435897,0.733333333,0.800000000,0.500000000,0.692307692,0.900000000,1.000000000,0.500000000,0.866666667,85.670566501,27.183846032,0.862139869,0.704631309,85.977845189,28.556667499,0.871910605,0.714116325,0.794765577,0.917130606,0.927097417,0.875365097,0.978829737,0.897317460,0.726262448,0.839701353,0.644618777,0.954933567,0.807906119
TE10,2024-12-10,NaN,0.923076923,1.000000000,0.960000000,0.900000000,1.000000000,0.769230769,0.923076923,1.000000000,0.894736842,NaN,0.400000000,NaN,0.444444444,0.166666667,NaN,NaN,0.235294118,0.000000000,0.218750000,NaN,NaN,NaN,0.523076923,0.687782805,-0.164705882,NaN,1.000000000,NaN,0.515555556,0.675986842,-0.160431287,0.818181818,0.500000000,0.625000000,0.655172414,0.718750000,0.585365854,0.590909091,0.631578947,0.363636364,0.090909091,0.750000000,0.366666667,0.370370370,0.500000000,0.400000000,0.437500000,77.539933276,37.845168343,0.618660856,0.499057527,84.415798326,34.825140190,0.542760616,0.492660881,0.913172369,0.825138905,0.869774713,0.923308330,0.816241095,0.836157931,0.763592572,0.756855686,0.701177631,0.915460177,0.826007512
KS20,2024-12-20,NaN,0.846153846,NaN,0.800000000,0.923076923,0.666666667,0.285714286,0.312500000,NaN,0.275862069,NaN,NaN,NaN,0.666666667,NaN,NaN,0.500000000,0.437500000,NaN,0.533333333,NaN,-0.214285714,NaN,NaN,-0.125000000,NaN,NaN,NaN,NaN,0.133333333,-0.257471264,0.390804598,0.478260870,0.439024390,0.461538462,0.454545455,0.478260870,0.418604651,0.500000000,0.450000000,0.800000000,0.517241379,1.000000000,0.656250000,NaN,0.666666667,1.000000000,0.750000000,2.673740612,10.659818961,0.146520186,0.103705019,3.527017607,11.822010441,0.105429453,0.114002889,0.859313973,0.928485676,0.891623417,0.870873741,0.912373093,0.887201583,0.742945312,0.842541351,0.752812213,0.931861816,0.733078412
CY17,2025-04-17,0.923076923,NaN,NaN,0.960000000,0.928571429,1.000000000,0.962962963,1.000000000,1.000000000,0.980769231,1.000,NaN,NaN,0.913043478,0.947368421,NaN,0.882352941,0.750000000,0.357142857,0.674418605,-0.076923077,0.080610022,-0.157533099,NaN,0.250000000,NaN,NaN,0.642857143,NaN,0.046956522,0.306350626,-0.259394104,1.000000000,0.777777778,NaN,0.882352941,0.933333333,0.888888889,0.640000000,0.857142857,0.409090909,0.444444444,0.200000000,0.388888889,0.682926829,0.421052632,0.590909091,0.597560976,33.710983134,13.151605922,0.336451547,0.220394545,74.865217074,30.251087438,0.791579209,0.558174548,0.849773920,0.804557478,0.830056083,0.793389687,0.866722480,0.838265775,0.792273726,0.752014375,0.760705775,0.924517176,0.823841678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RU10,2024-12-10,NaN,1.000000000,NaN,0.933333333,0.857142857,1.000000000,0.857142857,0.952380952,0.875000000,0.916666667,NaN,0.555555556,NaN,0.600000000,0.500000000,NaN,0.700000000,0.318181818,0.272727273,0.395348837,NaN,0.157142857,NaN,0.444444444,0.634199134,-0.189754690,NaN,0.602272727,NaN,0.333333333,0.521317829,-0.187984496,1.000000000,0.631578947,0.571428571,0.714285714,0.843750000,0.637931034,0.526315789,0.678899083,0.444444444,0.272727273,0.285714286,0.315789474,0.666666667,0.512820513,0.571428571,0.571428571,33.423653323,18.615019035,0.335884471,0.250472139,75.938950863,55.060336270,0.612756671,0.465079795,0.882619942,0.875157114,0.884644794,0.913986194,0.855303394,0.890747746,0.689337362,0.933808211,0.643281102,0.847687280,0.735393623
SH02,2025-04-02,0.956521739,0.928571429,0.888888889,0.934782609,0.956521739,0.913043478,0.875000000,0.750000000,1.000000000,0.891891892,0.950,NaN,0.714285714,0.794871795,0.750000000,0.842105263,0.250000000,0.076923077,0.181818182,0.166666667,0.006521739,0.625000000,-0.618478261,NaN,0.673076923,NaN,0.174603175,0.818181818,-0.643578644,0.139910814,0.725225225,-0.585314411,0.555555556,NaN,NaN,0.555555556,0.642857143,0.346153846,0.625000000,0.554347826,0.500000000,0.125000000,0.375000000,0.346153846,0.512820513,0.535714286,0.500000000,0.516853933,79.144418347,21.419024243,0.530238804,0.436898931,87.054086410,19.021758229,0.684610052,0.568817813,0.873133830,0.909790958,0.897269693,0.910452495,0.884086890,0.811004890,0.779562113,0.691967419,0.705998463,0.930042361,0.853125763
MC09,2025-05-09,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,0.857142857,0.714285714,0.736842105,1.000,0.857142857,0.900000000,0.916666667,0.833333333,1.000000000,0.533333333,0.375000000,NaN,0.517241379,0.000000000,NaN,NaN,0.142857143,0.482142857,-0.339285714,0.100000000,NaN,NaN,0.083333333,0.219600726,-0.136267393,0.718750000,0.571428571,0.681818182,0.676470588,0.666666667,0.578947368,0.714285714,0.663043478,0.685714286,0.571428571,0.695652174,0.666666667,0.444444444,0.600000000,0.444444444,0.468750000,29.478950211,13.145776948,0.291933950,0.220521447,7.144749197,9.025256722,0.145832569,0.113699580,0.813171808,0.831770102,0.861995768,0.806465390,0.917526147,0.837370946,0.773930916,0.784928306,0.782043796,0.889813586,0.765818036
VC20,2024-11-20,0.909090909,1.000000000,1.000000000,0.961538462,0.900000000,1.000000000,1.000000000,0.866666667,0.812500000,0.888888889,1.000,NaN,NaN,1.000000000,1.000000000,1.000000000,0.937500000,0.375000000,0.294117647,0.560975610,-0.090909091,0.062500000,-0.153409091,NaN,0.491666667,NaN,NaN,0.518382353,NaN,-0.038461538,0.327913279,-0.366374818,1.000000000,0.750000000,0.555555556,0.825000000,0.960784314,0.696969697,0.545454545,0.769230769,0.789473684,0.666666667,0.444444444,0.675000000,0.606060606,0.714285714,0.640000000,0.645569620,80.491537545,21.126056690,0.757716271,0.585180428,85.568614236,16.837282781,0.759785036,0.625746279,0.884698878,0.872315188,0.929941170,0.919642857,0.940239483,0.920729585,0.838854318,0.860664305,0.688576212,0.980794865,0.989132423
PO03,2024-12-03,NaN,NaN,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,1.000000000,1.000000000,0.875,NaN,0.000000000,0.400000000,0.400000000,0.400000000,0.833333333,0.285714286,0.272727273,0.500000000,NaN,0.166666667,NaN,NaN,NaN,NaN,1.000000000,0.727272727,0.272727273,0.600000000,0.500000000,0.100000000,0.894736842,0.777777778,NaN,0.818181818,0.925000000,0.647058824,0.578947368,0.776315789,0.809523810,0.700000000,0.666666667,0.756756757,0.640000000,0.888888889,0.687500000,0.700000000,77.469864884,28.005587183,0.692054886,0.516104288,78.687626054,26.615758573,0.745038761,0.575511198,0.910460017,0.803740322,0.931348735,0.954132448,0.908565023,0.833358451,0.753918709,0.743994751,0.750826396,0.922722152,0.757011022

In [42]:
for pseudonym in df.index:
    if pseudonym in opponent_dict:
        df.loc[pseudonym, 'opponent'] = opponent_dict[pseudonym]

**QUESTIONNAIRE SCORES**

In [12]:
questionnaire_data_df.set_index('pseudonym', inplace=True)

In [13]:
questionnaire_data_df

                date  GAD_total  AQ_total  BIS_total
pseudonym
AW17      2024-10-17          5         9         11
AE14      2025-03-14          3         2         17
AL01      2025-04-01          5         3         17
AW19      2025-03-19         11         2         20
AS12      2025-05-12          4         7         20
...              ...        ...       ...        ...
YY15      2025-01-15          4         7         16
YL15      2025-01-15          0         1         11
ZZ30      2025-05-30          2         8         13
ZH17      2025-10-17          5         9         21
ZS20      2024-11-20          2         4         17

[103 rows x 4 columns]

In [14]:
for pseudonym in df.index:
    if pseudonym not in questionnaire_data_df.index:
        print(f"Warning: {pseudonym} not found in questionnaire data.")

Warning: EM17 not found in questionnaire data.
Warning: BC03 not found in questionnaire data.
Warning: PO03 not found in questionnaire data.

In [15]:
for pseudonym in questionnaire_data_df.index:
    if pseudonym not in df.index:
        print(f"Warning: {pseudonym} not found in individual_analyses_table_6.csv")

In [16]:
for pseudonym in questionnaire_data_df.index:
    if pseudonym not in df.index:
        print(f"Warning: {pseudonym} not found in individual_analyses_table_6.csv")

In [43]:
for pseudonym in df.index:
    if pseudonym in questionnaire_data_df.index:
        df.loc[pseudonym, 'AQ_total'] = questionnaire_data_df.loc[pseudonym, 'AQ_total']
        df.loc[pseudonym, 'GAD_total'] = questionnaire_data_df.loc[pseudonym, 'GAD_total']
        df.loc[pseudonym, 'BIS_total'] = questionnaire_data_df.loc[pseudonym, 'BIS_total']
    else:
        df.loc[pseudonym, 'AQ_total'] = np.nan
        df.loc[pseudonym, 'GAD_total'] = np.nan
        df.loc[pseudonym, 'BIS_total'] = np.nan

In [18]:
df

,experiment_date,pH_H_first_vis_combined_solo_sep1,pH_H_first_vis_combined_solo_sep2,pH_H_first_vis_combined_solo_sep4,pH_H_first_vis_combined_solo_all_seps,pH_H_first_vis_first_solo_all_seps,pH_H_first_vis_second_solo_all_seps,pH_H_first_vis_social_sep1,pH_H_first_vis_social_sep2,pH_H_first_vis_social_sep4,pH_H_first_vis_social_all_seps,pH_L_first_vis_combined_solo_sep1,pH_L_first_vis_combined_solo_sep2,pH_L_first_vis_combined_solo_sep4,pH_L_first_vis_combined_solo_all_seps,pH_L_first_vis_first_solo_all_seps,pH_L_first_vis_second_solo_all_seps,pH_L_first_vis_social_sep1,pH_L_first_vis_social_sep2,pH_L_first_vis_social_sep4,pH_L_first_vis_social_all_seps,sensory_effect_solo_sep1,sensory_effect_social_sep1,solo-social_sensory_effect_sep1,sensory_effect_solo_sep2,sensory_effect_social_sep2,solo-social_sensory_effect_sep2,sensory_effect_solo_sep4,sensory_effect_social_sep4,solo-social_sensory_effect_sep4,sensory_effect_solo_all_seps,sensory_effect_social_all_seps,solo-social_sensory_effect_all_seps,pH_opp_visible_sep_1,pH_opp_visible_sep_2,pH_opp_visible_sep_4,pH_opp_visible_all_seps,pH_opp_not_visible_sep_1,pH_opp_not_visible_sep_2,pH_opp_not_visible_sep_4,pH_opp_not_visible_all_seps,p_win_other_visible_sep_1,p_win_other_visible_sep_2,p_win_other_visible_sep_4,p_win_other_visible,p_win_other_not_visible_sep_1,p_win_other_not_visible_sep_2,p_win_other_not_visible_sep_4,p_win_other_not_visible,solo_centre_occupancy_between_trials,solo_distance_travelled_between_trials,solo_central_tendency_at_slice_onset,solo_central_tendency_throughout_trajectory,social_centre_occupancy_between_trials,social_distance_travelled_between_trials,social_central_tendency_at_slice_onset,social_central_tendency_throughout_trajectory,rt_by_traj_efficiency_first_solo,rt_by_traj_efficiency_second_solo,rt_by_traj_efficiency_combined_solo,rt_combined_solos,traj_efficiency_combined_solos,rt_by_traj_efficiency_wins,rt_by_traj_efficiency_losses,rt_wins,rt_losses,traj_efficiency_wins,traj_efficiency_losses,opponent,AQ_total,GAD_total,BIS_total
TK10,2024-12-10,NaN,1.000000000,NaN,1.000000000,1.000000000,1.000000000,0.800000000,0.875000000,1.000000000,0.882352941,NaN,0.785714286,0.750000000,0.814814815,0.833333333,0.800000000,0.416666667,0.181818182,0.153846154,0.234042553,NaN,0.383333333,NaN,0.214285714,0.693181818,-0.478896104,NaN,0.846153846,NaN,0.185185185,0.648310388,-0.463125203,0.600000000,0.500000000,0.300000000,0.475000000,0.583333333,0.511111111,0.454545455,0.524271845,0.600000000,0.476190476,0.500000000,0.512195122,0.642857143,0.678571429,0.461538462,0.623188406,81.527574142,20.557037892,0.742367399,0.589442460,79.566697439,41.918692348,0.619212796,0.509680777,0.945914274,0.851731597,0.944118107,0.935539210,0.952697004,0.882218665,0.661307717,0.884800414,0.604361135,0.879636915,0.718254298,TE10,4.0,18.0,16.0
IN04,2025-02-04,0.909090909,NaN,1.000000000,0.947368421,0.909090909,1.000000000,0.875000000,NaN,NaN,0.941176471,1.000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,NaN,0.769230769,-0.090909091,-0.125000000,0.034090909,NaN,NaN,NaN,0.000000000,NaN,NaN,-0.052631579,0.171945701,-0.224577280,0.933333333,NaN,NaN,0.884615385,0.958333333,0.875000000,0.714285714,0.897435897,0.733333333,0.800000000,0.500000000,0.692307692,0.900000000,1.000000000,0.500000000,0.866666667,85.670566501,27.183846032,0.862139869,0.704631309,85.977845189,28.556667499,0.871910605,0.714116325,0.794765577,0.917130606,0.927097417,0.875365097,0.978829737,0.897317460,0.726262448,0.839701353,0.644618777,0.954933567,0.807906119,JL04,7.0,2.0,15.0
TE10,2024-12-10,NaN,0.923076923,1.000000000,0.960000000,0.900000000,1.000000000,0.769230769,0.923076923,1.000000000,0.894736842,NaN,0.400000000,NaN,0.444444444,0.166666667,NaN,NaN,0.235294118,0.000000000,0.218750000,NaN,NaN,NaN,0.523076923,0.687782805,-0.164705882,NaN,1.000000000,NaN,0.515555556,0.675986842,-0.160431287,0.818181818,0.500000000,0.625000000,0.655172414,0.718750000,0.585365854,0.590909091,0.631578947,0.363636364,0.090909091,0.750000000,0.366666667,0.370370370,0.500000000,0.400000000,0.437500000,77.539933276,37.845168343,0.618660856,0.499057527,84.415798326,34.825140190,0.542760616,0.492660881,0.913172369,0.825138905,0.869774713,0.923308330,0.816241095,0.836157931,0.763592572,0.756855686,0.701177631,0.915460177,0.826007512,TK10,5.0,0.0,20.0
KS20,2024-12-20,NaN,0.846153846,NaN,0.800000000,0.923076923,0.666666667,0.285714286,0.312500000,NaN,0.275862069,NaN,NaN,NaN,0.666666667,NaN,NaN,0.500000000,0.437500000,NaN,0.533333333,NaN,-0.214285714,NaN,NaN,-0.125000000,NaN,NaN,NaN,NaN,0.133333333,-0.257471264,0.390804598,0.478260870,0.439024390,0.461538462,0.454545455,0.478260870,0.418604651,0.500000000,0.450000000,0.800000000,0.517241379,1.000000000,0.656250000,NaN,0.666666667,1.000000000,0.750000000,2.673740612,10.659818961,0.146520186,0.103705019,3.527017607,11.822010441,0.105429453,0.114002889,0.859313973,0.928485676,0.891623417,0.870873741,0.912373093,0.887201583,0.742945312,0.842541351,0.752812213,0.931861816,0.733078412,CS20,2.0,0.0,23.0
CY17,2025-04-17,0.923076923,NaN,NaN,0.960000000,0.928571429,1.000000000,0.962962963,1.000000000,1.000000000,0.980769231,1.000,NaN,NaN,0.913043478,0.947368421,NaN,0.882352941,0.750000000,0.357142857,0.674418605,-0.076923077,0.080610022,-0.157533099,NaN,0.250000000,NaN,NaN,0.642857143,NaN,0.046956522,0.306350626,-0.259394104,1.000000000,0.777777778,NaN,0.882352941,0.933333333,0.888888889,0.640000000,0.857142857,0.409090909,0.444444444,0.200000000,0.388888889,0.682926829,0.421052632,0.590909091,0.597560976,33.710983134,13.151605922,0.336451547,0.220394545,74.865217074,30.251087438,0.791579209,0.558174548,0.849773920,0.804557478,0.830056083,0.793389687,0.866722480,0.838265775,0.792273726,0.752014375,0.760705775,0.924517176,0.823841678,RL17,3.0,3.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RU10,2024-12-10,NaN,1.000000000,NaN,0.933333333,0.857142857,1.000000000,0.857142857,0.952380952,0.875000000,0.916666667,NaN,0.555555556,NaN,0.600000000,0.500000000,NaN,0.700000000,0.318181818,0.272727273,0.395348837,NaN,0.157142857,NaN,0.444444444,0.634199134,-0.189754690,NaN,0.602272727,NaN,0.333333333,0.521317829,-0.187984496,1.000000000,0.631578947,0.571428571,0.714285714,0.843750000,0.637931034,0.526315789,0.678899083,0.444444444,0.272727273,0.285714286,0.315789474,0.666666667,0.512820513,0.571428571,0.571428571,33.423653323,18.615019035,0.335884471,0.250472139,75.938950863,55.060336270,0.612756671,0.465079795,0.882619942,0.875157114,0.884644794,0.913986194,0.855303394,0.890747746,0.689337362,0.933808211,0.643281102,0.847687280,0.735393623,RK10,0.0,0.0,8.0
SH02,2025-04-02,0.956521739,0.928571429,0.888888889,0.934782609,0.956521739,0.913043478,0.875000000,0.750000000,1.000000000,0.891891892,0.950,NaN,0.714285714,0.794871795,0.750000000,0.842105263,0.250000000,0.076923077,0.181818182,0.166666667,0.006521739,0.625000000,-0.618478261,NaN,0.673076923,NaN,0.174603175,0.818181818,-0.643578644,0.139910814,0.725225225,-0.585314411,0.555555556,NaN,NaN,0.555555556,0.642857143,0.346153846,0.625000000,0.554347826,0.500000000,0.125000000,0.375000000,0.346153846,0.512820513,0.535714286,0.500000000,0.516853933,79.144418347,21.419024243,0.530238804,0.436898931,87.054086410,19.021758229,0.684610052,0.568817813,0.873133830,0.909790958,0.897269693,0.910452495,0.884086890,0.811004890,0.779562113,0.691967419,0.705998463,0.930042361,0.853125763,ML02,2.0,6.0,17.0
MC09,2025-05-09,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,0.857142857,0.714285714,0.736842105,1.000,0.857142857,0.900000000,0.916666667,0.833333333,1.000000000,0.533333333,0.375000000,NaN,0.517241379,0.000000000,NaN,NaN,0.142857143,0.482142857,-0.339285714,0.100000000,NaN,NaN,0.083333333,0.219600726,-0.136267393,0.718750000,0.571428571,0.681818182,0.676470588,0.666666667,0.578947368,0.714285714,0.663043478,0.685714286,0.571428571,0.695652174,0.666666667,0.444444444,0.600000000,0.444444444,0.468750000,29.478950211,13.145776948,0.291933950,0.220521447,7.144749197,9.025256722,0.145832569,0.113699580,0.813171808,0.831770102,0.861995768,0.806465390,0.917526147,0.837370946,0.773930916,0.784928306,0.782043796,0.889813586,0.765818036,AM09,2.0,5.0,16.0
VC20,2024-11-20,0.909090909,1.000000000,1.000000000,0.961538462,0.900000000,1.000000000,1.000000000,0.866666667,0.812500000,0.888888889,1.000,NaN,NaN,1.000000000,1.000000000,1.000000000,0.937500000,0.375000000,0.294117647,0.560975610,-0.090909091,0.062500000,-0.153409091,NaN,0.491666667,NaN,NaN,0.518382353,NaN,-0.038461538,0.327913279,-0.366374818,1.000000000,0.750000000,0.555555556,0.825000000,0.960784314,0.696969697,0.545454545,0.769230769,0.789473684,0.666666667,0.444444444,0.675000000,0.606060606,0.714285714,0.640000000,0.645569620,80.491537545,21.126056690,0.757716271,0.585180428,85.568614236,16.837282781,0.759785036,0.625746279,0.884698878,0.872315188,0.929941170,0.919642857,0.940239483,0.920729585,0.838854318,0.860664305,0.688576212,0.980794865,0.989132423,ZS20,3.0,4.0,17.0
PO03,2024-12-03,NaN,NaN,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,1.000000000,1.000000000,0.875,NaN,0.000000000,0.400000000,0.400000000,0.400000000,0.833333333,0.285714286,0.272727273,0.500000000,NaN,0.166666667,NaN,NaN,NaN,NaN,1.000000000,0.727272727,0.272727273,0.600000000,0.500000000,0.100000000,0.894736842,0.777777778,NaN,0.818181818,0.925000000,0.647058824,0.578947368,0.776315789,0.809523810,0.700000000,0.666666667,0.756756757,0.640000000,0.888888889,0.687500000,0.700000000,77.469864884,28.005587183,0.692054886,0.516104288,78.687626054,26.615758573,0.745038761,0.575511198,0.910460017,0.803740322,0.931348735,0.954132448,0.908565023,0.833358451,0.753918709,0.743994751,0.750826396,0.922722152,0.757011022,NN03,NaN,NaN,NaN

**PLAYER SCORES**

In [19]:
social_files, ordered_solos = identify_filepaths.get_filenames(data_folder=data_folder)

In [20]:
import re
pseudo_tuples_list = []
experiment_dates_socials = []
for file in social_files:
     # match the session number and the pseudonym string
    match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?_.*?)_Social\.json', file)
    if match:
        session, date, time, pseudonyms = match.groups()
        pseudo_tuples = pseudonyms.split('_')[0::]
        pseudo_tuples_list.append(pseudo_tuples)
        experiment_dates_socials.append(date)

In [21]:
df_socials, social_lists = prepare_data.prepare_data(data_folder, social_files, combine=False)

filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250417_1/2025-04-17_12-22-26_CY17_RL17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241112_2/2024-11-12_15-23-24_FA12_SL12_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241210_1/2024-12-10_14-21-17_TE10_TK10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250509_1/2025-05-09_12-30-13_AM09_MC09_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250401_2/2025-04-01_15-29-49_AL01_NL01_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250319_1/2025-03-19_13-29-40_HL19_AW19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250115_2/2025-01-15_16-27-23_YL15_RR15_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250522_1/2025-05-22_09-26-39_SS22_AD22_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241113_1/2024-11-13_14-18-54_NK13_RD13_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241119_1/2024-11-19_14-24-49_AV19_XG19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/240927_1/2024-09-27_14-25-20_SH27_EN27_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241017_1/2024-10-17_14-28-40_SP17_AW17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250410_1/2025-04-10_12-29-00_AR10_MY10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241219_1/2024-12-19_15-28-24_JU19_SY19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250512_2/2025-05-12_12-23-08_NO12_AS12_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250204_1/2025-02-04_15-55-44_IN04_JL04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241120_2/2024-11-20_15-16-21_ZS20_VC20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250314_1/2025-03-14_12-12-57_KC14_WL14_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250604_1/2025-06-04_15-23-18_MP04_SH04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241203_1/2024-12-03_14-31-51_PO03_NN03_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_3/2025-03-18_17-27-32_HM18_SC18_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250627_2/2025-06-27_18-00-17_KB27_VB27_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250421_1/2025-04-21_09-29-53_NM21_KC21_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250521_1/2025-05-21_09-31-42_EH21_SP21_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_2/2025-03-18_16-22-17_JK18_HL18_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250404_1/2025-04-04_10-31-29_JW04_JI04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241112_1/2024-11-12_13-31-14_KA12_WM12_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250530_1/2025-05-30_11-33-24_ZZ30_VW30_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241210_2/2024-12-10_15-20-11_RK10_RU10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250411_1/2025-04-11_09-29-35_IN11_CW11_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250524_1/2025-05-24_10-28-19_JP24_IP24_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250401_1/2025-04-01_14-27-01_IS01_HQ01_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250620_1/2025-06-20_15-30-03_JK20_DD20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/240913_1/2024-09-13_11-31-00_YW13_JL13_Social.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250115_1/2025-01-15_15-21-27_YY15_MR15_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250319_2/2025-03-19_14-33-16_PT19_JL19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250520_1/2025-05-20_14-29-04_CY20_MJ20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241113_2/2024-11-13_15-28-07_YL13_HC13_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241119_2/2024-11-19_15-22-56_SB19_HH19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250512_1/2025-05-12_09-35-29_TG12_SC12_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250204_2/2025-02-04_17-11-07_DB04_GG04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241017_2/2024-10-17_16-41-38_ZH17_EM17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250502_1/2025-05-02_11-21-38_JC02_KS02_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241203_2/2024-12-03_15-27-28_EX03_BC03_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241120_1/2024-11-20_14-17-44_JS20_RR20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250314_2/2025-03-14_13-10-49_AE14_JL14_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250402_1/2025-04-02_16-26-25_SH02_ML02_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250523_1/2025-05-23_18-05-58_JW23_YL23_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_1/2025-03-18_14-22-29_SJ18_CD18_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250627_1/2025-06-27_16-56-08_RH27_TF27_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241220_1/2024-12-20_17-44-50_KS20_CS20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250314_3/2025-03-14_14-24-05_MA14_RM14_Social.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250421_2/2025-04-21_10-29-08_LM21_LS21_Social.json
Loading complete.
Preprocessing complete.

Pseudonym lists

Separate first and second solos

In [22]:
first_solos = ordered_solos[::2]
second_solos = ordered_solos[1::2]

In [23]:
first_solo_pseudo_list = []
second_solo_pseudo_list = []
first_solo_dates = []
second_solo_dates = []
solo_dates = {}


for first_solo, second_solo in zip(first_solos, second_solos):
   # match the session number and the pseudonym string
    first_match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?)_FirstSolo\.json', first_solo)
    second_match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?)_SecondSolo\.json', second_solo)

    if first_match:
        session, date, time, pseudonyms = first_match.groups()
        first_pseudo = pseudonyms.split('_')[0::]
        first_solo_pseudo_list.append(first_pseudo)
        first_solo_dates.append(date)

        
    if second_match:
        session, date, time, pseudonyms = second_match.groups()
        second_pseudo = pseudonyms.split('_')[0::]
        second_solo_pseudo_list.append(second_pseudo)
        second_solo_dates.append(date)

for i, pseudonym in enumerate(first_solo_pseudo_list):
    player = pseudonym[0]
    if player not in solo_dates:
        solo_dates[player] = []
    solo_dates[player] = first_solo_dates[i]

Load data

In [24]:
df_solos, solos_lists = prepare_data.prepare_data(data_folder, ordered_solos, combine=False)
df_first_solos, first_solos_lists = prepare_data.prepare_data(data_folder, first_solos, combine=False)
df_second_solos, second_solos_lists = prepare_data.prepare_data(data_folder, second_solos, combine=False)

filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250417_1/2025-04-17_12-09-51_CY17_FirstSolo.json

Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250417_1/2025-04-17_12-46-27_CY17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250417_1/2025-04-17_12-10-56_RL17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250417_1/2025-04-17_12-46-05_RL17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241112_2/2024-11-12_15-13-34_FA12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241112_2/2024-11-12_15-44-54_FA12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241112_2/2024-11-12_15-11-45_SL12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241112_2/2024-11-12_15-45-35_SL12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241210_1/2024-12-10_14-13-47_TE10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241210_1/2024-12-10_14-45-41_TE10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241210_1/2024-12-10_14-12-58_TK10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241210_1/2024-12-10_14-45-09_TK10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250509_1/2025-05-09_12-18-03_AM09_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250509_1/2025-05-09_12-53-10_AM09_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250509_1/2025-05-09_12-18-53_MC09_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250509_1/2025-05-09_12-53-00_MC09_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250401_2/2025-04-01_15-17-03_AL01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250401_2/2025-04-01_15-52-21_AL01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250401_2/2025-04-01_15-17-26_NL01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250401_2/2025-04-01_15-52-54_NL01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250319_1/2025-03-19_13-17-55_HL19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250319_1/2025-03-19_13-51-16_HL19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250319_1/2025-03-19_13-17-46_AW19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250319_1/2025-03-19_13-51-26_AW19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250115_2/2025-01-15_16-14-40_YL15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250115_2/2025-01-15_16-50-13_YL15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250115_2/2025-01-15_16-14-58_RR15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250115_2/2025-01-15_16-50-37_RR15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250522_1/2025-05-22_09-15-24_SS22_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250522_1/2025-05-22_09-49-04_SS22_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250522_1/2025-05-22_09-15-49_AD22_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250522_1/2025-05-22_09-49-03_AD22_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241113_1/2024-11-13_14-12-43_NK13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241113_1/2024-11-13_14-37-06_NK13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241113_1/2024-11-13_14-12-41_RD13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241113_1/2024-11-13_14-37-20_RD13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241119_1/2024-11-19_14-18-18_AV19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241119_1/2024-11-19_14-44-00_AV19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241119_1/2024-11-19_14-18-44_XG19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241119_1/2024-11-19_14-44-31_XG19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/240927_1/2024-09-27_14-14-31_SH27_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/240927_1/2024-09-27_14-45-55_SH27_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/240927_1/2024-09-27_14-14-42_EN27_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/240927_1/2024-09-27_14-45-46_EN27_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241017_1/2024-10-17_14-20-28_SP17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241017_1/2024-10-17_14-50-03_SP17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241017_1/2024-10-17_14-20-50_AW17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241017_1/2024-10-17_14-51-22_AW17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250410_1/2025-04-10_12-16-12_AR10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250410_1/2025-04-10_12-53-58_AR10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250410_1/2025-04-10_12-16-26_MY10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250410_1/2025-04-10_12-53-34_MY10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241219_1/2024-12-19_15-20-18_JU19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241219_1/2024-12-19_15-51-58_JU19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241219_1/2024-12-19_15-22-13_SY19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241219_1/2024-12-19_15-51-33_SY19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250512_2/2025-05-12_12-10-42_NO12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250512_2/2025-05-12_12-44-45_NO12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250512_2/2025-05-12_12-10-18_AS12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250512_2/2025-05-12_12-45-03_AS12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250204_1/2025-02-04_15-42-50_IN04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250204_1/2025-02-04_16-19-25_IN04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241120_2/2024-11-20_15-10-00_ZS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241120_2/2024-11-20_15-40-08_ZS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241120_2/2024-11-20_15-10-17_VC20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241120_2/2024-11-20_15-39-49_VC20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250314_1/2025-03-14_12-03-08_KC14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250314_1/2025-03-14_12-36-26_KC14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250314_1/2025-03-14_12-03-22_WL14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250314_1/2025-03-14_12-35-54_WL14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250604_1/2025-06-04_15-11-03_MP04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250604_1/2025-06-04_15-46-01_MP04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250604_1/2025-06-04_15-11-26_SH04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250604_1/2025-06-04_15-45-49_SH04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241203_1/2024-12-03_14-20-13_PO03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241203_1/2024-12-03_14-52-05_PO03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241203_1/2024-12-03_14-19-21_NN03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/241203_1/2024-12-03_14-52-30_NN03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_3/2025-03-18_17-15-58_HM18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_3/2025-03-18_17-48-42_HM18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_3/2025-03-18_17-16-10_SC18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_3/2025-03-18_17-49-19_SC18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250627_2/2025-06-27_17-48-29_KB27_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250627_2/2025-06-27_18-20-57_KB27_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250627_2/2025-06-27_17-48-13_VB27_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250627_2/2025-06-27_18-21-07_VB27_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250421_1/2025-04-21_09-18-28_NM21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250421_1/2025-04-21_09-51-36_NM21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250421_1/2025-04-21_09-18-42_KC21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250421_1/2025-04-21_09-51-56_KC21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250521_1/2025-05-21_09-21-15_EH21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250521_1/2025-05-21_09-55-07_EH21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250521_1/2025-05-21_09-21-16_SP21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250521_1/2025-05-21_09-55-08_SP21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_2/2025-03-18_16-10-59_JK18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_2/2025-03-18_16-44-49_JK18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_2/2025-03-18_16-11-11_HL18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250318_2/2025-03-18_16-45-29_HL18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/pseudonymised_json_files/250404_1/2025-04-04_10-18-59_JW04_FirstSolo.json
Loading complete.
Preprocessing complete.

Create combined solos list

In [25]:
# combined solos
combined_solos = []

for trial_list_idx in range(0, len(solos_lists), 2):

    print(ordered_solos[trial_list_idx], ordered_solos[trial_list_idx + 1]) 

    # concatenate the trial lists for the 2 solos of this session
    trial_list_combined = solos_lists[trial_list_idx] + solos_lists[trial_list_idx + 1]

    combined_solos.append(trial_list_combined)

250417_1/2025-04-17_12-09-51_CY17_FirstSolo.json 250417_1/2025-04-17_12-46-27_CY17_SecondSolo.json
250417_1/2025-04-17_12-10-56_RL17_FirstSolo.json 250417_1/2025-04-17_12-46-05_RL17_SecondSolo.json
241112_2/2024-11-12_15-13-34_FA12_FirstSolo.json 241112_2/2024-11-12_15-44-54_FA12_SecondSolo.json
241112_2/2024-11-12_15-11-45_SL12_FirstSolo.json 241112_2/2024-11-12_15-45-35_SL12_SecondSolo.json
241210_1/2024-12-10_14-13-47_TE10_FirstSolo.json 241210_1/2024-12-10_14-45-41_TE10_SecondSolo.json
241210_1/2024-12-10_14-12-58_TK10_FirstSolo.json 241210_1/2024-12-10_14-45-09_TK10_SecondSolo.json
250509_1/2025-05-09_12-18-03_AM09_FirstSolo.json 250509_1/2025-05-09_12-53-10_AM09_SecondSolo.json
250509_1/2025-05-09_12-18-53_MC09_FirstSolo.json 250509_1/2025-05-09_12-53-00_MC09_SecondSolo.json
250401_2/2025-04-01_15-17-03_AL01_FirstSolo.json 250401_2/2025-04-01_15-52-21_AL01_SecondSolo.json
250401_2/2025-04-01_15-17-26_NL01_FirstSolo.json 250401_2/2025-04-01_15-52-54_NL01_SecondSolo.json
250319_1/2025-03-19_13-17-55_HL19_FirstSolo.json 250319_1/2025-03-19_13-51-16_HL19_SecondSolo.json
250319_1/2025-03-19_13-17-46_AW19_FirstSolo.json 250319_1/2025-03-19_13-51-26_AW19_SecondSolo.json
250115_2/2025-01-15_16-14-40_YL15_FirstSolo.json 250115_2/2025-01-15_16-50-13_YL15_SecondSolo.json
250115_2/2025-01-15_16-14-58_RR15_FirstSolo.json 250115_2/2025-01-15_16-50-37_RR15_SecondSolo.json
250522_1/2025-05-22_09-15-24_SS22_FirstSolo.json 250522_1/2025-05-22_09-49-04_SS22_SecondSolo.json
250522_1/2025-05-22_09-15-49_AD22_FirstSolo.json 250522_1/2025-05-22_09-49-03_AD22_SecondSolo.json
241113_1/2024-11-13_14-12-43_NK13_FirstSolo.json 241113_1/2024-11-13_14-37-06_NK13_SecondSolo.json
241113_1/2024-11-13_14-12-41_RD13_FirstSolo.json 241113_1/2024-11-13_14-37-20_RD13_SecondSolo.json
241119_1/2024-11-19_14-18-18_AV19_FirstSolo.json 241119_1/2024-11-19_14-44-00_AV19_SecondSolo.json
241119_1/2024-11-19_14-18-44_XG19_FirstSolo.json 241119_1/2024-11-19_14-44-31_XG19_SecondSolo.json
240927_1/2024-09-27_14-14-31_SH27_FirstSolo.json 240927_1/2024-09-27_14-45-55_SH27_SecondSolo.json
240927_1/2024-09-27_14-14-42_EN27_FirstSolo.json 240927_1/2024-09-27_14-45-46_EN27_SecondSolo.json
241017_1/2024-10-17_14-20-28_SP17_FirstSolo.json 241017_1/2024-10-17_14-50-03_SP17_SecondSolo.json
241017_1/2024-10-17_14-20-50_AW17_FirstSolo.json 241017_1/2024-10-17_14-51-22_AW17_SecondSolo.json
250410_1/2025-04-10_12-16-12_AR10_FirstSolo.json 250410_1/2025-04-10_12-53-58_AR10_SecondSolo.json
250410_1/2025-04-10_12-16-26_MY10_FirstSolo.json 250410_1/2025-04-10_12-53-34_MY10_SecondSolo.json
241219_1/2024-12-19_15-20-18_JU19_FirstSolo.json 241219_1/2024-12-19_15-51-58_JU19_SecondSolo.json
241219_1/2024-12-19_15-22-13_SY19_FirstSolo.json 241219_1/2024-12-19_15-51-33_SY19_SecondSolo.json
250512_2/2025-05-12_12-10-42_NO12_FirstSolo.json 250512_2/2025-05-12_12-44-45_NO12_SecondSolo.json
250512_2/2025-05-12_12-10-18_AS12_FirstSolo.json 250512_2/2025-05-12_12-45-03_AS12_SecondSolo.json
250204_1/2025-02-04_15-42-50_IN04_FirstSolo.json 250204_1/2025-02-04_16-19-25_IN04_SecondSolo.json
241120_2/2024-11-20_15-10-00_ZS20_FirstSolo.json 241120_2/2024-11-20_15-40-08_ZS20_SecondSolo.json
241120_2/2024-11-20_15-10-17_VC20_FirstSolo.json 241120_2/2024-11-20_15-39-49_VC20_SecondSolo.json
250314_1/2025-03-14_12-03-08_KC14_FirstSolo.json 250314_1/2025-03-14_12-36-26_KC14_SecondSolo.json
250314_1/2025-03-14_12-03-22_WL14_FirstSolo.json 250314_1/2025-03-14_12-35-54_WL14_SecondSolo.json
250604_1/2025-06-04_15-11-03_MP04_FirstSolo.json 250604_1/2025-06-04_15-46-01_MP04_SecondSolo.json
250604_1/2025-06-04_15-11-26_SH04_FirstSolo.json 250604_1/2025-06-04_15-45-49_SH04_SecondSolo.json
241203_1/2024-12-03_14-20-13_PO03_FirstSolo.json 241203_1/2024-12-03_14-52-05_PO03_SecondSolo.json
241203_1/2024-12-03_14-19-21_NN03_FirstSolo.json 241203_1/2024-12-03_14-52-30_NN03_SecondSolo.json
250318_3/2025-03-18_17-15-58_HM18_FirstSolo.json 250318_3/2025-03-18_17-48-42_HM18_SecondSolo.json
250318_3/2025-03-18_17-16-10_SC18_FirstSolo.json 250318_3/2025-03-18_17-49-19_SC18_SecondSolo.json
250627_2/2025-06-27_17-48-29_KB27_FirstSolo.json 250627_2/2025-06-27_18-20-57_KB27_SecondSolo.json
250627_2/2025-06-27_17-48-13_VB27_FirstSolo.json 250627_2/2025-06-27_18-21-07_VB27_SecondSolo.json
250421_1/2025-04-21_09-18-28_NM21_FirstSolo.json 250421_1/2025-04-21_09-51-36_NM21_SecondSolo.json
250421_1/2025-04-21_09-18-42_KC21_FirstSolo.json 250421_1/2025-04-21_09-51-56_KC21_SecondSolo.json
250521_1/2025-05-21_09-21-15_EH21_FirstSolo.json 250521_1/2025-05-21_09-55-07_EH21_SecondSolo.json
250521_1/2025-05-21_09-21-16_SP21_FirstSolo.json 250521_1/2025-05-21_09-55-08_SP21_SecondSolo.json
250318_2/2025-03-18_16-10-59_JK18_FirstSolo.json 250318_2/2025-03-18_16-44-49_JK18_SecondSolo.json
250318_2/2025-03-18_16-11-11_HL18_FirstSolo.json 250318_2/2025-03-18_16-45-29_HL18_SecondSolo.json
250404_1/2025-04-04_10-18-59_JW04_FirstSolo.json 250404_1/2025-04-04_10-53-32_JW04_SecondSolo.json
250404_1/2025-04-04_10-19-11_JI04_FirstSolo.json 250404_1/2025-04-04_10-53-11_JI04_SecondSolo.json
241112_1/2024-11-12_13-19-22_KA12_FirstSolo.json 241112_1/2024-11-12_13-50-23_KA12_SecondSolo.json
241112_1/2024-11-12_13-18-59_WM12_FirstSolo.json 241112_1/2024-11-12_13-50-20_WM12_SecondSolo.json
250530_1/2025-05-30_11-18-37_ZZ30_FirstSolo.json 250530_1/2025-05-30_11-57-32_ZZ30_SecondSolo.json
250530_1/2025-05-30_11-18-19_VW30_FirstSolo.json 250530_1/2025-05-30_11-56-49_VW30_SecondSolo.json
241210_2/2024-12-10_15-12-18_RK10_FirstSolo.json 241210_2/2024-12-10_15-42-27_RK10_SecondSolo.json
241210_2/2024-12-10_15-11-46_RU10_FirstSolo.json 241210_2/2024-12-10_15-41-53_RU10_SecondSolo.json
250411_1/2025-04-11_09-17-58_IN11_FirstSolo.json 250411_1/2025-04-11_09-51-07_IN11_SecondSolo.json
250411_1/2025-04-11_09-18-11_CW11_FirstSolo.json 250411_1/2025-04-11_09-51-19_CW11_SecondSolo.json
250524_1/2025-05-24_10-16-54_JP24_FirstSolo.json 250524_1/2025-05-24_10-53-00_JP24_SecondSolo.json
250524_1/2025-05-24_10-17-04_IP24_FirstSolo.json 250524_1/2025-05-24_10-52-48_IP24_SecondSolo.json
250401_1/2025-04-01_14-15-29_IS01_FirstSolo.json 250401_1/2025-04-01_14-48-25_IS01_SecondSolo.json
250401_1/2025-04-01_14-15-24_HQ01_FirstSolo.json 250401_1/2025-04-01_14-48-51_HQ01_SecondSolo.json
250620_1/2025-06-20_15-18-58_JK20_FirstSolo.json 250620_1/2025-06-20_15-51-01_JK20_SecondSolo.json
250620_1/2025-06-20_15-19-07_DD20_FirstSolo.json 250620_1/2025-06-20_15-50-46_DD20_SecondSolo.json
240913_1/2024-09-13_11-23-37_YW13_FirstSolo.json 240913_1/2024-09-13_11-53-34_YW13_SecondSolo.json
240913_1/2024-09-13_11-23-50_JL13_FirstSolo.json 240913_1/2024-09-13_11-53-56_JL13_SecondSolo.json
250115_1/2025-01-15_15-12-13_YY15_FirstSolo.json 250115_1/2025-01-15_15-47-11_YY15_SecondSolo.json
250115_1/2025-01-15_15-12-39_MR15_FirstSolo.json 250115_1/2025-01-15_15-46-04_MR15_SecondSolo.json
250319_2/2025-03-19_14-22-02_PT19_FirstSolo.json 250319_2/2025-03-19_14-54-33_PT19_SecondSolo.json
250319_2/2025-03-19_14-22-13_JL19_FirstSolo.json 250319_2/2025-03-19_14-55-00_JL19_SecondSolo.json
250520_1/2025-05-20_14-15-25_CY20_FirstSolo.json 250520_1/2025-05-20_14-53-46_CY20_SecondSolo.json
250520_1/2025-05-20_14-15-00_MJ20_FirstSolo.json 250520_1/2025-05-20_14-53-15_MJ20_SecondSolo.json
241113_2/2024-11-13_15-22-20_YL13_FirstSolo.json 241113_2/2024-11-13_15-51-39_YL13_SecondSolo.json
241113_2/2024-11-13_15-21-50_HC13_FirstSolo.json 241113_2/2024-11-13_15-51-16_HC13_SecondSolo.json
241119_2/2024-11-19_15-15-53_SB19_FirstSolo.json 241119_2/2024-11-19_15-47-53_SB19_SecondSolo.json
241119_2/2024-11-19_15-14-19_HH19_FirstSolo.json 241119_2/2024-11-19_15-47-29_HH19_SecondSolo.json
250512_1/2025-05-12_09-24-24_TG12_FirstSolo.json 250512_1/2025-05-12_09-58-02_TG12_SecondSolo.json
250512_1/2025-05-12_09-24-39_SC12_FirstSolo.json 250512_1/2025-05-12_09-57-44_SC12_SecondSolo.json
250204_2/2025-02-04_16-58-53_DB04_FirstSolo.json 250204_2/2025-02-04_17-32-55_DB04_SecondSolo.json
250204_2/2025-02-04_16-58-37_GG04_FirstSolo.json 250204_2/2025-02-04_17-33-22_GG04_SecondSolo.json
241017_2/2024-10-17_16-36-00_ZH17_FirstSolo.json 241017_2/2024-10-17_17-11-46_ZH17_SecondSolo.json
241017_2/2024-10-17_16-35-45_EM17_FirstSolo.json 241017_2/2024-10-17_17-12-29_EM17_SecondSolo.json
250502_1/2025-05-02_11-09-55_JC02_FirstSolo.json 250502_1/2025-05-02_11-44-02_JC02_SecondSolo.json
250502_1/2025-05-02_11-10-14_KS02_FirstSolo.json 250502_1/2025-05-02_11-43-42_KS02_SecondSolo.json
241203_2/2024-12-03_15-19-51_EX03_FirstSolo.json 241203_2/2024-12-03_15-53-11_EX03_SecondSolo.json
241203_2/2024-12-03_15-20-09_BC03_FirstSolo.json 241203_2/2024-12-03_15-52-57_BC03_SecondSolo.json
241120_1/2024-11-20_14-12-06_JS20_FirstSolo.json 241120_1/2024-11-20_14-42-16_JS20_SecondSolo.json
241120_1/2024-11-20_14-12-33_RR20_FirstSolo.json 241120_1/2024-11-20_14-41-56_RR20_SecondSolo.json
250314_2/2025-03-14_12-59-24_AE14_FirstSolo.json 250314_2/2025-03-14_13-32-14_AE14_SecondSolo.json
250314_2/2025-03-14_12-59-36_JL14_FirstSolo.json 250314_2/2025-03-14_13-32-33_JL14_SecondSolo.json
250402_1/2025-04-02_16-13-59_SH02_FirstSolo.json 250402_1/2025-04-02_16-48-31_SH02_SecondSolo.json
250402_1/2025-04-02_16-14-13_ML02_FirstSolo.json 250402_1/2025-04-02_16-48-09_ML02_SecondSolo.json
250523_1/2025-05-23_17-54-31_JW23_FirstSolo.json 250523_1/2025-05-23_18-27-58_JW23_SecondSolo.json
250523_1/2025-05-23_17-54-43_YL23_FirstSolo.json 250523_1/2025-05-23_18-27-42_YL23_SecondSolo.json
250318_1/2025-03-18_14-09-51_SJ18_FirstSolo.json 250318_1/2025-03-18_14-44-19_SJ18_SecondSolo.json
250318_1/2025-03-18_14-10-34_CD18_FirstSolo.json 250318_1/2025-03-18_14-44-40_CD18_SecondSolo.json
250627_1/2025-06-27_16-45-51_RH27_FirstSolo.json 250627_1/2025-06-27_17-15-39_RH27_SecondSolo.json
250627_1/2025-06-27_16-45-33_TF27_FirstSolo.json 250627_1/2025-06-27_17-15-18_TF27_SecondSolo.json
241220_1/2024-12-20_17-36-27_KS20_FirstSolo.json 241220_1/2024-12-20_18-06-10_KS20_SecondSolo.json
241220_1/2024-12-20_17-36-54_CS20_FirstSolo.json 241220_1/2024-12-20_18-06-44_CS20_SecondSolo.json
250314_3/2025-03-14_14-12-29_MA14_FirstSolo.json 250314_3/2025-03-14_14-46-57_MA14_SecondSolo.json
250314_3/2025-03-14_14-12-49_RM14_FirstSolo.json 250314_3/2025-03-14_14-46-27_RM14_SecondSolo.json
250421_2/2025-04-21_10-18-48_LM21_FirstSolo.json 250421_2/2025-04-21_10-50-34_LM21_SecondSolo.json
250421_2/2025-04-21_10-18-58_LS21_FirstSolo.json 250421_2/2025-04-21_10-50-54_LS21_SecondSolo.json

In [26]:
ordered_solo_pseudo_list = []

for first_solo in (ordered_solos):
   # match the session number and the pseudonym string
    first_match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?)_FirstSolo\.json', first_solo)

    if first_match:
        session, date, time, pseudonyms = first_match.groups()
        first_pseudo = pseudonyms.split('_')[0::]
        ordered_solo_pseudo_list.append(first_pseudo)

In [27]:
import analysis.player_scores as player_scores

In [28]:
proportion_scores_all_sessions = player_scores.proportion_score_sessions_df(social_lists)
proportion_wins_all_sessions = player_scores.proportion_wins_sessions(social_lists)

In [29]:
proportion_scores = {}
proportion_wins = {}

In [30]:
for i, tuple in enumerate(pseudo_tuples_list):
    player0 = tuple[0]
    player1 = tuple[1]

    if player0 not in proportion_scores:
        proportion_scores[player0] = []
        proportion_wins[player0] = []
    if player1 not in proportion_scores:
        proportion_scores[player1] = []
        proportion_wins[player1] = []
    
    proportion_scores[player0] = proportion_scores_all_sessions[i][0]
    proportion_wins[player0] = proportion_wins_all_sessions[i][0]
    proportion_scores[player1] = proportion_scores_all_sessions[i][1]
    proportion_wins[player1] = proportion_wins_all_sessions[i][1]

In [44]:
for pseudonym in df.index:
    df.loc[pseudonym, 'proportion_score'] = proportion_scores.get(pseudonym, np.nan)
    df.loc[pseudonym, 'proportion_wins'] = proportion_wins.get(pseudonym, np.nan)

SCORES PER UNIT TIME

Socials

In [ ]:
# trial logic
scores_per_unit_time = [(0, 0) for _ in range(len(social_lists))]
delta_times_list = []
for trial_list_index in range(len(social_lists)):
    # define trial
    trial_list = social_lists[trial_list_index]
    delta_times = []
    for trial_index in range(len(trial_list)):
        trial = trial_list[trial_index]
        # cut trials to only return timepoints between slice onset and server-selected trigger activation
        slice_onset = trial[trial['eventDescription'] == globals.SLICE_ONSET]
        slice_onset_index = slice_onset.index[0] - trial.index[0]
        selected_trigger_activation = trial[trial['eventDescription'] == globals.SELECTED_TRIGGER_ACTIVATION]
        selected_trigger_activation_index = selected_trigger_activation.index[0] - trial.index[0]

        # extract application time between slice onset and server-selected trigger activation
        time_app_onset = trial['timeApplication'].iloc[slice_onset_index]
        time_app_trigger = trial['timeApplication'].iloc[selected_trigger_activation_index]        
        time = time_app_trigger - time_app_onset
        delta_time = time.total_seconds()
        delta_times.append(delta_time)
        
    total_time = sum(delta_times)
    delta_times_list.append(total_time)

    # access final trial event log event for the final player scores
    final_trial = trial_list[-1]
    final_trial_trial_end = final_trial[final_trial['eventDescription'] == 'trial end']
    
    # flexibly index player scores
    player0_score = final_trial_trial_end[globals.PLAYER_SCORE_DICT[0]['score']].item()
    player1_score = final_trial_trial_end[globals.PLAYER_SCORE_DICT[1]['score']].item()

    # score per unit time as final score divided by total time spent playing (active trials)
    score_per_time_unit_p0 = player0_score/total_time
    score_per_time_unit_p1 = player1_score/total_time
    print(player0_score, player1_score)
    print(score_per_time_unit_p0, score_per_time_unit_p1)
    scores_per_unit_time[trial_list_index] = (score_per_time_unit_p0, score_per_time_unit_p1)

3830.0 2690.0
10.139517644878616 7.121488894183676
3700.0 960.0
10.612635920617482 2.753548779403455
2400.0 2870.0
7.421104384017415 8.874403992554159
2120.0 3440.0
5.5773035315906885 9.049964221071683
4350.0 1060.0
12.210629142140144 2.9754636530272536
2420.0 3060.0
8.072855856156387 10.207825999933283
1380.0 4190.0
3.7283391599889772 11.320102232140446
2490.0 2610.0
9.17603617348236 9.618254784252596
2320.0 2390.0
8.171977865211678 8.418546162868928
1420.0 2920.0
4.622952634269101 9.506353304271673
1520.0 2540.0
5.045425425624787 8.43117143492563
1840.0 2540.0
5.407391080743516 7.464550731026376
4700.0 1370.0
11.955849844701142 3.4850030398384177
2770.0 2980.0
7.703324665934342 8.287331229055717
2630.0 2400.0
8.104901462272146 7.39610779827116
1970.0 670.0
12.103710985500124 4.116490538215778
1720.0 4090.0
4.177200741210271 9.932994785784889
450.0 3890.0
0.6970540944957511 6.025645394641049
3670.0 2190.0
11.787301832010073 7.033839512834349
3010.0 1110.0
10.760837700827262 3.968282341501083
990.0 3960.0
2.1401379632371857 8.560551852948743
2920.0 nan
8.550837952835685 nan
1510.0 3480.0
4.137496403666206 9.535422175336686
2780.0 2640.0
8.272160015711153 7.855576417797641
2110.0 3320.0
6.667909657724505 10.491687233955146
3030.0 2450.0
9.100219546550777 7.358263329719275
1460.0 2420.0
4.0854588445986595 6.771787947896408
2400.0 3580.0
6.676533098912838 9.959161872544982
3020.0 2650.0
9.76489874576019 8.568536978895532
2000.0 3300.0
6.8224923929209815 11.257112448319619
2730.0 3260.0
6.903230863763601 8.24341854061148
2480.0 3100.0
8.887519127876349 11.109398909845435
2590.0 2610.0
7.36699585855368 7.42388385746143
2150.0 2920.0
6.506909429873675 8.837290946619131
2030.0 3700.0
5.553245502691819 10.121678995054054
3670.0 1870.0
10.914141098729855 5.561156363657991
3450.0 1470.0
9.825700615174298 4.186602870813397
2050.0 3270.0
5.979622612890899 9.53822728983085
3850.0 1050.0
7.373176575130754 2.010866338672024
2380.0 3100.0
7.546260479155834 9.82916280898449
2780.0 2600.0
7.640280216896013 7.145585814363177
2390.0 4730.0
5.012047788512554 9.919241020780076
3160.0 2690.0
9.57735380139114 8.152873963842458
2930.0 2140.0
7.970685288508884 5.821592668057683
1540.0 4640.0
3.899691823055282 11.749720817517213
1960.0 3540.0
5.186872977185698 9.368127724100699
2660.0 3080.0
8.332132587409083 9.64773246963157
3300.0 1780.0
8.224832014037046 4.436424540904832
1900.0 3630.0
5.574512156837433 10.650252173326253
1630.0 2140.0
5.47433611080325 7.187165200686476
2780.0 1690.0
8.557664188638007 5.202321035538932
1880.0 2770.0
4.183141494761061 6.163458478983052
2000.0 3030.0
6.079249091152261 9.210062373095676

In [33]:
scores_per_unit_time_dict = {}

for i, tuple in enumerate(pseudo_tuples_list):
    player0 = tuple[0]
    player1 = tuple[1]

    if player0 not in scores_per_unit_time_dict:
        scores_per_unit_time_dict[player0] = []
    if player1 not in scores_per_unit_time_dict:
        scores_per_unit_time_dict[player1] = []
    
    scores_per_unit_time_dict[player0] = scores_per_unit_time[i][0]
    scores_per_unit_time_dict[player1] = scores_per_unit_time[i][1]

Solos

In [34]:
# trial logic
scores_per_unit_time_comb_solos = [0 for _ in range(len(combined_solos))]
delta_times_list_comb_solos = []
for trial_list_index in range(len(combined_solos)):
    # define trial
    trial_list = combined_solos[trial_list_index]
    delta_times = []
    for trial_index in range(len(trial_list)):
        trial = trial_list[trial_index]
        # cut trials to only return timepoints between slice onset and server-selected trigger activation
        slice_onset = trial[trial['eventDescription'] == globals.SLICE_ONSET]
        slice_onset_index = slice_onset.index[0] - trial.index[0]
        selected_trigger_activation = trial[trial['eventDescription'] == globals.SELECTED_TRIGGER_ACTIVATION]
        selected_trigger_activation_index = selected_trigger_activation.index[0] - trial.index[0]

        # extract application time between slice onset and server-selected trigger activation
        time_app_onset = trial['timeApplication'].iloc[slice_onset_index]
        time_app_trigger = trial['timeApplication'].iloc[selected_trigger_activation_index]        
        time = time_app_trigger - time_app_onset
        delta_time = time.total_seconds()
        delta_times.append(delta_time)
        
    total_time = sum(delta_times)
    delta_times_list.append(total_time)

    # access final trial event log event for the final player scores
    final_trial = trial_list[-1]
    final_trial_trial_end = final_trial[final_trial['eventDescription'] == 'trial end']
    
    # flexibly index player scores
    player0_score = final_trial_trial_end[globals.PLAYER_SCORE_DICT[0]['score']].item()
    # score per unit time as final score divided by total time spent playing (active trials)
    score_per_time_unit_p0 = player0_score/total_time

    scores_per_unit_time_comb_solos[trial_list_index] = score_per_time_unit_p0

In [35]:
scores_per_unit_time_dict_comb_solos = {}

for i, pseudonym in enumerate(ordered_solo_pseudo_list):
    player = pseudonym[0]

    if player not in scores_per_unit_time_dict_comb_solos:
        scores_per_unit_time_dict_comb_solos[player] = []
    
    scores_per_unit_time_dict_comb_solos[player] = scores_per_unit_time_comb_solos[i]

In [45]:
for pseudonym in df.index:
    df.loc[pseudonym, 'scores_per_unit_time_socials'] = scores_per_unit_time_dict.get(pseudonym, np.nan)

In [46]:
for pseudonym in df.index:
    df.loc[pseudonym, 'scores_per_unit_time_solos'] = scores_per_unit_time_dict_comb_solos.get(pseudonym, np.nan)

In [38]:
df

,experiment_date,pH_H_first_vis_combined_solo_sep1,pH_H_first_vis_combined_solo_sep2,pH_H_first_vis_combined_solo_sep4,pH_H_first_vis_combined_solo_all_seps,pH_H_first_vis_first_solo_all_seps,pH_H_first_vis_second_solo_all_seps,pH_H_first_vis_social_sep1,pH_H_first_vis_social_sep2,pH_H_first_vis_social_sep4,pH_H_first_vis_social_all_seps,pH_L_first_vis_combined_solo_sep1,pH_L_first_vis_combined_solo_sep2,pH_L_first_vis_combined_solo_sep4,pH_L_first_vis_combined_solo_all_seps,pH_L_first_vis_first_solo_all_seps,pH_L_first_vis_second_solo_all_seps,pH_L_first_vis_social_sep1,pH_L_first_vis_social_sep2,pH_L_first_vis_social_sep4,pH_L_first_vis_social_all_seps,sensory_effect_solo_sep1,sensory_effect_social_sep1,solo-social_sensory_effect_sep1,sensory_effect_solo_sep2,sensory_effect_social_sep2,solo-social_sensory_effect_sep2,sensory_effect_solo_sep4,sensory_effect_social_sep4,solo-social_sensory_effect_sep4,sensory_effect_solo_all_seps,sensory_effect_social_all_seps,solo-social_sensory_effect_all_seps,pH_opp_visible_sep_1,pH_opp_visible_sep_2,pH_opp_visible_sep_4,pH_opp_visible_all_seps,pH_opp_not_visible_sep_1,pH_opp_not_visible_sep_2,pH_opp_not_visible_sep_4,pH_opp_not_visible_all_seps,p_win_other_visible_sep_1,p_win_other_visible_sep_2,p_win_other_visible_sep_4,p_win_other_visible,p_win_other_not_visible_sep_1,p_win_other_not_visible_sep_2,p_win_other_not_visible_sep_4,p_win_other_not_visible,solo_centre_occupancy_between_trials,solo_distance_travelled_between_trials,solo_central_tendency_at_slice_onset,solo_central_tendency_throughout_trajectory,social_centre_occupancy_between_trials,social_distance_travelled_between_trials,social_central_tendency_at_slice_onset,social_central_tendency_throughout_trajectory,rt_by_traj_efficiency_first_solo,rt_by_traj_efficiency_second_solo,rt_by_traj_efficiency_combined_solo,rt_combined_solos,traj_efficiency_combined_solos,rt_by_traj_efficiency_wins,rt_by_traj_efficiency_losses,rt_wins,rt_losses,traj_efficiency_wins,traj_efficiency_losses,opponent,AQ_total,GAD_total,BIS_total,proportion_score,proportion_wins,scores_per_unit_time_socials,scores_per_unit_time_solos
TK10,2024-12-10,NaN,1.000000000,NaN,1.000000000,1.000000000,1.000000000,0.800000000,0.875000000,1.000000000,0.882352941,NaN,0.785714286,0.750000000,0.814814815,0.833333333,0.800000000,0.416666667,0.181818182,0.153846154,0.234042553,NaN,0.383333333,NaN,0.214285714,0.693181818,-0.478896104,NaN,0.846153846,NaN,0.185185185,0.648310388,-0.463125203,0.600000000,0.500000000,0.300000000,0.475000000,0.583333333,0.511111111,0.454545455,0.524271845,0.600000000,0.476190476,0.500000000,0.512195122,0.642857143,0.678571429,0.461538462,0.623188406,81.527574142,20.557037892,0.742367399,0.589442460,79.566697439,41.918692348,0.619212796,0.509680777,0.945914274,0.851731597,0.944118107,0.935539210,0.952697004,0.882218665,0.661307717,0.884800414,0.604361135,0.879636915,0.718254298,TE10,4.0,18.0,16.0,0.544592030,0.568345324,8.874403993,4.702344676
IN04,2025-02-04,0.909090909,NaN,1.000000000,0.947368421,0.909090909,1.000000000,0.875000000,NaN,NaN,0.941176471,1.000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,NaN,0.769230769,-0.090909091,-0.125000000,0.034090909,NaN,NaN,NaN,0.000000000,NaN,NaN,-0.052631579,0.171945701,-0.224577280,0.933333333,NaN,NaN,0.884615385,0.958333333,0.875000000,0.714285714,0.897435897,0.733333333,0.800000000,0.500000000,0.692307692,0.900000000,1.000000000,0.500000000,0.866666667,85.670566501,27.183846032,0.862139869,0.704631309,85.977845189,28.556667499,0.871910605,0.714116325,0.794765577,0.917130606,0.927097417,0.875365097,0.978829737,0.897317460,0.726262448,0.839701353,0.644618777,0.954933567,0.807906119,JL04,7.0,2.0,15.0,0.746212121,0.754385965,12.103710986,6.206709122
TE10,2024-12-10,NaN,0.923076923,1.000000000,0.960000000,0.900000000,1.000000000,0.769230769,0.923076923,1.000000000,0.894736842,NaN,0.400000000,NaN,0.444444444,0.166666667,NaN,NaN,0.235294118,0.000000000,0.218750000,NaN,NaN,NaN,0.523076923,0.687782805,-0.164705882,NaN,1.000000000,NaN,0.515555556,0.675986842,-0.160431287,0.818181818,0.500000000,0.625000000,0.655172414,0.718750000,0.585365854,0.590909091,0.631578947,0.363636364,0.090909091,0.750000000,0.366666667,0.370370370,0.500000000,0.400000000,0.437500000,77.539933276,37.845168343,0.618660856,0.499057527,84.415798326,34.825140190,0.542760616,0.492660881,0.913172369,0.825138905,0.869774713,0.923308330,0.816241095,0.836157931,0.763592572,0.756855686,0.701177631,0.915460177,0.826007512,TK10,5.0,0.0,20.0,0.455407970,0.431654676,7.421104384,5.769605717
KS20,2024-12-20,NaN,0.846153846,NaN,0.800000000,0.923076923,0.666666667,0.285714286,0.312500000,NaN,0.275862069,NaN,NaN,NaN,0.666666667,NaN,NaN,0.500000000,0.437500000,NaN,0.533333333,NaN,-0.214285714,NaN,NaN,-0.125000000,NaN,NaN,NaN,NaN,0.133333333,-0.257471264,0.390804598,0.478260870,0.439024390,0.461538462,0.454545455,0.478260870,0.418604651,0.500000000,0.450000000,0.800000000,0.517241379,1.000000000,0.656250000,NaN,0.666666667,1.000000000,0.750000000,2.673740612,10.659818961,0.146520186,0.103705019,3.527017607,11.822010441,0.105429453,0.114002889,0.859313973,0.928485676,0.891623417,0.870873741,0.912373093,0.887201583,0.742945312,0.842541351,0.752812213,0.931861816,0.733078412,CS20,2.0,0.0,23.0,0.621923937,0.626984127,8.557664189,5.534092096
CY17,2025-04-17,0.923076923,NaN,NaN,0.960000000,0.928571429,1.000000000,0.962962963,1.000000000,1.000000000,0.980769231,1.000,NaN,NaN,0.913043478,0.947368421,NaN,0.882352941,0.750000000,0.357142857,0.674418605,-0.076923077,0.080610022,-0.157533099,NaN,0.250000000,NaN,NaN,0.642857143,NaN,0.046956522,0.306350626,-0.259394104,1.000000000,0.777777778,NaN,0.882352941,0.933333333,0.888888889,0.640000000,0.857142857,0.409090909,0.444444444,0.200000000,0.388888889,0.682926829,0.421052632,0.590909091,0.597560976,33.710983134,13.151605922,0.336451547,0.220394545,74.865217074,30.251087438,0.791579209,0.558174548,0.849773920,0.804557478,0.830056083,0.793389687,0.866722480,0.838265775,0.792273726,0.752014375,0.760705775,0.924517176,0.823841678,RL17,3.0,3.0,18.0,0.587423313,0.570469799,10.139517645,5.766086817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RU10,2024-12-10,NaN,1.000000000,NaN,0.933333333,0.857142857,1.000000000,0.857142857,0.952380952,0.875000000,0.916666667,NaN,0.555555556,NaN,0.600000000,0.500000000,NaN,0.700000000,0.318181818,0.272727273,0.395348837,NaN,0.157142857,NaN,0.444444444,0.634199134,-0.189754690,NaN,0.602272727,NaN,0.333333333,0.521317829,-0.187984496,1.000000000,0.631578947,0.571428571,0.714285714,0.843750000,0.637931034,0.526315789,0.678899083,0.444444444,0.272727273,0.285714286,0.315789474,0.666666667,0.512820513,0.571428571,0.571428571,33.423653323,18.615019035,0.335884471,0.250472139,75.938950863,55.060336270,0.612756671,0.465079795,0.882619942,0.875157114,0.884644794,0.913986194,0.855303394,0.890747746,0.689337362,0.933808211,0.643281102,0.847687280,0.735393623,RK10,0.0,0.0,8.0,0.467372134,0.481481481,8.568536979,5.202948116
SH02,2025-04-02,0.956521739,0.928571429,0.888888889,0.934782609,0.956521739,0.913043478,0.875000000,0.750000000,1.000000000,0.891891892,0.950,NaN,0.714285714,0.794871795,0.750000000,0.842105263,0.250000000,0.076923077,0.181818182,0.166666667,0.006521739,0.625000000,-0.618478261,NaN,0.673076923,NaN,0.174603175,0.818181818,-0.643578644,0.139910814,0.725225225,-0.585314411,0.555555556,NaN,NaN,0.555555556,0.642857143,0.346153846,0.625000000,0.554347826,0.500000000,0.125000000,0.375000000,0.346153846,0.512820513,0.535714286,0.500000000,0.516853933,79.144418347,21.419024243,0.530238804,0.436898931,87.054086410,19.021758229,0.684610052,0.568817813,0.873133830,0.909790958,0.897269693,0.910452495,0.884086890,0.811004890,0.779562113,0.691967419,0.705998463,0.930042361,0.853125763,ML02,2.0,6.0,17.0,0.463414634,0.489510490,8.332132587,6.014491644
MC09,2025-05-09,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,0.857142857,0.714285714,0.736842105,1.000,0.857142857,0.900000000,0.916666667,0.833333333,1.000000000,0.533333333,0.375000000,NaN,0.517241379,0.000000000,NaN,NaN,0.142857143,0.482142857,-0.339285714,0.100000000,NaN,NaN,0.083333333,0.219600726,-0.136267393,0.718750000,0.571428571,0.681818182,0.676470588,0.666666667,0.578947368,0.714285714,0.663043478,0.685714286,0.571428571,0.695652174,0.666666667,0.444444444,0.600000000,0.444444444,0.468750000,29.478950211,13.145776948,0.291933950,0.220521447,7.144749197,9.025256722,0.145832569,0.113699580,0.813171808,0.831770102,0.861995768,0.806465390,0.917526147,0.837370946,0.773930916,0.784928306,0.782043796,0.889813586,0.765818036,AM09,2.0,5.0,16.0,0.618705036,0.620437956,9.049964221,7.013917900
VC20,2024-11-20,0.909090909,1.000000000,1.000000000,0.961538462,0.900000000,1.000000000,1.000000000,0.866666667,0.812500000,0.888888889,1.000,NaN,NaN,1.000000000,1.000000000,1.000000000,0.937500000,0.375000000,0.294117647,0.560975610,-0.090909091,0.062500000,-0.153409091,NaN,0.491666667,NaN,NaN,0.518382353,NaN,-0.038461538,0.327913279,-0.366374818,1.000000000,0.750000000,0.555555556,0.825000000,0.960784314,0.696969697,0.545454545,0.769230769,0.789473684,0.666666667,0.444444444,0.675000000,0.606060606,0.714285714,0.640000000,0.645569620,80.491537545,21.126056690,0.757716271,0.585180428,85.568614236,16.837282781,0.759785036,0.625746279,0.884698878,0.872315188,0.929941170,0.919642857,0.940239483,0.920729585,0.838854318,0.860664305,0.688576212,0.980794865,0.989132423,ZS20,3.0,4.0,17.0,0.703958692,0.669014085,9.932994786,6.675133394
PO03,2024-12-03,NaN,NaN,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,1.000000000,1.000000000,0.875,NaN,0.000000000,0.400000000,0.400000000,0.400000000,0.833333333,0.285714286,0.272727273,0.500000000,NaN,0.166666667,NaN,NaN,NaN,NaN,1.000000000,0.727272727,0.272727273,0.600000000,0.500000000,0.100000000,0.894736842,0.777777778,NaN,0.818181818,0.925000000,0.647058824,0.578947368,0.776315789,0.809523810,0.700000000,0.666666667,0.756756757,0.640000000,0.888888889,0.687500000,0.700000000,77.469864884,28.005587183,0.692054886,0.516104288,78.687626054,26.615758573,0.745038761,0.575511198,0.910460017,0.803740322,0.931348735,0.954132448,0.908565023,0.833358451,0.753918709,0.743994751,0.750826396,0.922722152,0.757011022,NN03,NaN,NaN,NaN,0.730582524,0.702970297,10.760837701,3.486404440

In [ ]:
df.to_csv('individual_analyses_and_questionnaire_data_table.csv')

In [ ]:
df = pd.read_csv('individual_analyses_and_questionnaire_data_table.csv', index_col=0)

In [38]:
df_2 = pd.read_csv('individual_analyses_and_questionnaire_data_table.csv', index_col=0)

In [39]:
df['proportion_score'] = df_2['proportion_score']
df['proportion_wins'] = df_2['proportion_wins']
df['scores_per_unit_time_socials'] = df_2['scores_per_unit_time_socials']
df['scores_per_unit_time_solos'] = df_2['scores_per_unit_time_solos']

In [49]:
print(pseudo_tuples_list)

[['CY17', 'RL17'], ['FA12', 'SL12'], ['TE10', 'TK10'], ['AM09', 'MC09'], ['AL01', 'NL01'], ['HL19', 'AW19'], ['YL15', 'RR15'], ['SS22', 'AD22'], ['NK13', 'RD13'], ['AV19', 'XG19'], ['SH27', 'EN27'], ['SP17', 'AW17'], ['AR10', 'MY10'], ['JU19', 'SY19'], ['NO12', 'AS12'], ['IN04', 'JL04'], ['ZS20', 'VC20'], ['KC14', 'WL14'], ['MP04', 'SH04'], ['PO03', 'NN03'], ['HM18', 'SC18'], ['KB27', 'VB27'], ['NM21', 'KC21'], ['EH21', 'SP21'], ['JK18', 'HL18'], ['JW04', 'JI04'], ['KA12', 'WM12'], ['ZZ30', 'VW30'], ['RK10', 'RU10'], ['IN11', 'CW11'], ['JP24', 'IP24'], ['IS01', 'HQ01'], ['JK20', 'DD20'], ['YW13', 'JL13'], ['YY15', 'MR15'], ['PT19', 'JL19'], ['CY20', 'MJ20'], ['YL13', 'HC13'], ['SB19', 'HH19'], ['TG12', 'SC12'], ['DB04', 'GG04'], ['ZH17', 'EM17'], ['JC02', 'KS02'], ['EX03', 'BC03'], ['JS20', 'RR20'], ['AE14', 'JL14'], ['SH02', 'ML02'], ['JW23', 'YL23'], ['SJ18', 'CD18'], ['RH27', 'TF27'], ['KS20', 'CS20'], ['MA14', 'RM14'], ['LM21', 'LS21']]

In [ ]:
for pseudonym in pseudo_tuples_list:
    metric_a = df.loc[pseudonym,'social_central_tendency_at_slice_onset']
    metric_b = df.loc[pseudonym,'social_central_tendency_throughout_trajectory']

    if metric_a > 0.5 and metric_b > 0.5:
        df.loc['strategy_social'] = 0
    elif metric_a <= 0.5 and metric_b <= 0.5:
        df.loc['strategy_social'] = 1
    else:
        df.loc['strategy_social'] = np.nan

In [91]:
for pseudonym in pseudo_tuples_list:
    metric = df.loc[pseudonym,'social_centre_occupancy_between_trials']
    metric = metric[0]
    if metric > 50:
        df.loc[pseudonym, 'strategy_social'] = 0
    elif metric <= 50:
        df.loc[pseudonym, 'strategy_social'] = 1
    else:
        df.loc[pseudonym, 'strategy_social'] = np.nan

/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/1551209387.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]

In [92]:
for pseudonym in pseudo_tuples_list:
    metric = df.loc[pseudonym,'first_solo_centre_occupancy_between_trials']
    metric = metric[0]
    print(metric)
    if metric > 50:
        df.loc[pseudonym, 'strategy_first_solo'] = 0
    elif metric <= 50:
        df.loc[pseudonym, 'strategy_first_solo'] = 1
    else:
        df.loc[pseudonym, 'strategy_first_solo'] = np.nan

49.50403545561095
47.836663913181
84.00790695723411
68.0831833772664
50.00159557060447
62.11448085098984
64.59282380739572
79.00259471414212
61.419796339617285
75.14038801273927
74.3919905056523
38.29699089342984
82.36084392467126
83.82618530249943
82.13091825223363
84.1983401228174
78.0676887270571
12.451673002019431
57.98803931834634
71.88419586032508
23.524852556207424
64.70180193997517
69.47957529411158
17.33594051633572
64.0274595456294
21.668860246226867
23.85629233817788
70.68424308199161
67.22611139205205
80.13160650395264
80.50410050588967
76.75015684304238
77.67834531460313
18.279280422691446
78.06334668651374
83.79364179470865
73.46033765348294
62.76745468524341
80.23823994744781
79.03680661496865
73.83630950589561
74.33349841288168
78.81528181023701
74.87424034562096
82.4092172171984
62.16288283638154
77.14647720165658
75.6313174937722
32.73051468700659
78.97646350667445
4.001192822402047
48.85680311070161
68.13548854013807

/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3023039746.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]

In [93]:
for pseudonym in pseudo_tuples_list:
    metric = df.loc[pseudonym,'second_solo_centre_occupancy_between_trials']
    metric = metric[0]    
    if metric > 50:
        df.loc[pseudonym, 'strategy_second_solo'] = 0
    elif metric <= 50:
        df.loc[pseudonym, 'strategy_second_solo'] = 1
    else:
        df.loc[pseudonym, 'strategy_second_solo'] = np.nan

/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]
/var/folders/9k/5z7zk7v17ksb961yzn2v7hz40000gn/T/ipykernel_27898/3810041937.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  metric = metric[0]

In [97]:
df

,experiment_date,pH_H_first_vis_combined_solo_sep1,pH_H_first_vis_combined_solo_sep2,pH_H_first_vis_combined_solo_sep4,pH_H_first_vis_combined_solo_all_seps,pH_H_first_vis_first_solo_all_seps,pH_H_first_vis_second_solo_all_seps,pH_H_first_vis_social_sep1,pH_H_first_vis_social_sep2,pH_H_first_vis_social_sep4,pH_H_first_vis_social_all_seps,pH_L_first_vis_combined_solo_sep1,pH_L_first_vis_combined_solo_sep2,pH_L_first_vis_combined_solo_sep4,pH_L_first_vis_combined_solo_all_seps,pH_L_first_vis_first_solo_all_seps,pH_L_first_vis_second_solo_all_seps,pH_L_first_vis_social_sep1,pH_L_first_vis_social_sep2,pH_L_first_vis_social_sep4,pH_L_first_vis_social_all_seps,sensory_effect_solo_sep1,sensory_effect_social_sep1,solo-social_sensory_effect_sep1,sensory_effect_solo_sep2,sensory_effect_social_sep2,solo-social_sensory_effect_sep2,sensory_effect_solo_sep4,sensory_effect_social_sep4,solo-social_sensory_effect_sep4,sensory_effect_solo_all_seps,sensory_effect_social_all_seps,solo-social_sensory_effect_all_seps,pH_opp_visible_sep_1,pH_opp_visible_sep_2,pH_opp_visible_sep_4,pH_opp_visible_all_seps,pH_opp_not_visible_sep_1,pH_opp_not_visible_sep_2,pH_opp_not_visible_sep_4,pH_opp_not_visible_all_seps,p_win_other_visible_sep_1,p_win_other_visible_sep_2,p_win_other_visible_sep_4,p_win_other_visible,p_win_other_not_visible_sep_1,p_win_other_not_visible_sep_2,p_win_other_not_visible_sep_4,p_win_other_not_visible,solo_centre_occupancy_between_trials,solo_distance_travelled_between_trials,solo_central_tendency_at_slice_onset,solo_central_tendency_throughout_trajectory,first_solo_centre_occupancy_between_trials,first_solo_distance_travelled_between_trials,first_solo_central_tendency_at_slice_onset,first_solo_central_tendency_throughout_trajectory,second_solo_centre_occupancy_between_trials,second_solo_distance_travelled_between_trials,second_solo_central_tendency_at_slice_onset,second_solo_central_tendency_throughout_trajectory,social_centre_occupancy_between_trials,social_distance_travelled_between_trials,social_central_tendency_at_slice_onset,social_central_tendency_throughout_trajectory,rt_by_traj_efficiency_first_solo,rt_by_traj_efficiency_second_solo,rt_by_traj_efficiency_combined_solo,rt_combined_solos,traj_efficiency_combined_solos,rt_by_traj_efficiency_wins,rt_by_traj_efficiency_losses,rt_wins,rt_losses,traj_efficiency_wins,traj_efficiency_losses,opponent,AQ_total,GAD_total,BIS_total,proportion_score,proportion_wins,scores_per_unit_time_socials,scores_per_unit_time_solos,strategy_social,strategy_first_solo,strategy_second_solo
TK10,2024-12-10,NaN,1.000000000,NaN,1.000000000,1.000000000,1.000000000,0.800000000,0.875000000,1.000000000,0.882352941,NaN,0.785714286,0.750000000,0.814814815,0.833333333,0.800000000,0.416666667,0.181818182,0.153846154,0.234042553,NaN,0.383333333,NaN,0.214285714,0.693181818,-0.478896104,NaN,0.846153846,NaN,0.185185185,0.648310388,-0.463125203,0.600000000,0.500000000,0.300000000,0.475000000,0.583333333,0.511111111,0.454545455,0.524271845,0.600000000,0.476190476,0.500000000,0.512195122,0.642857143,0.678571429,0.461538462,0.623188406,81.527574142,20.557037892,0.742367399,0.589442460,81.965218898,18.924404326,0.757745799,0.591981801,81.156239198,21.942302736,0.726988999,0.586903119,79.566697439,41.918692348,0.619212796,0.509680777,0.945914274,0.851731597,0.944118107,0.935539210,0.952697004,0.882218665,0.661307717,0.884800414,0.604361135,0.879636915,0.718254298,TE10,4.0,18.0,16.0,0.544592030,0.568345324,8.874403993,4.702344676,0.0,0.0,0.0
IN04,2025-02-04,0.909090909,NaN,1.000000000,0.947368421,0.909090909,1.000000000,0.875000000,NaN,NaN,0.941176471,1.000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,NaN,0.769230769,-0.090909091,-0.125000000,0.034090909,NaN,NaN,NaN,0.000000000,NaN,NaN,-0.052631579,0.171945701,-0.224577280,0.933333333,NaN,NaN,0.884615385,0.958333333,0.875000000,0.714285714,0.897435897,0.733333333,0.800000000,0.500000000,0.692307692,0.900000000,1.000000000,0.500000000,0.866666667,85.670566501,27.183846032,0.862139869,0.704631309,84.198340123,28.780144484,0.905038610,0.708976285,87.705702965,24.977198171,0.819241128,0.700286334,85.977845189,28.556667499,0.871910605,0.714116325,0.794765577,0.917130606,0.927097417,0.875365097,0.978829737,0.897317460,0.726262448,0.839701353,0.644618777,0.954933567,0.807906119,JL04,7.0,2.0,15.0,0.746212121,0.754385965,12.103710986,6.206709122,0.0,0.0,0.0
TE10,2024-12-10,NaN,0.923076923,1.000000000,0.960000000,0.900000000,1.000000000,0.769230769,0.923076923,1.000000000,0.894736842,NaN,0.400000000,NaN,0.444444444,0.166666667,NaN,NaN,0.235294118,0.000000000,0.218750000,NaN,NaN,NaN,0.523076923,0.687782805,-0.164705882,NaN,1.000000000,NaN,0.515555556,0.675986842,-0.160431287,0.818181818,0.500000000,0.625000000,0.655172414,0.718750000,0.585365854,0.590909091,0.631578947,0.363636364,0.090909091,0.750000000,0.366666667,0.370370370,0.500000000,0.400000000,0.437500000,77.539933276,37.845168343,0.618660856,0.499057527,84.007906957,22.725054693,0.796074207,0.629631617,71.489248220,51.989790790,0.441247504,0.368483438,84.415798326,34.825140190,0.542760616,0.492660881,0.913172369,0.825138905,0.869774713,0.923308330,0.816241095,0.836157931,0.763592572,0.756855686,0.701177631,0.915460177,0.826007512,TK10,5.0,0.0,20.0,0.455407970,0.431654676,7.421104384,5.769605717,0.0,0.0,0.0
KS20,2024-12-20,NaN,0.846153846,NaN,0.800000000,0.923076923,0.666666667,0.285714286,0.312500000,NaN,0.275862069,NaN,NaN,NaN,0.666666667,NaN,NaN,0.500000000,0.437500000,NaN,0.533333333,NaN,-0.214285714,NaN,NaN,-0.125000000,NaN,NaN,NaN,NaN,0.133333333,-0.257471264,0.390804598,0.478260870,0.439024390,0.461538462,0.454545455,0.478260870,0.418604651,0.500000000,0.450000000,0.800000000,0.517241379,1.000000000,0.656250000,NaN,0.666666667,1.000000000,0.750000000,2.673740612,10.659818961,0.146520186,0.103705019,4.001192822,9.106169736,0.178307840,0.114903023,1.042870753,12.568588009,0.114732531,0.092507015,3.527017607,11.822010441,0.105429453,0.114002889,0.859313973,0.928485676,0.891623417,0.870873741,0.912373093,0.887201583,0.742945312,0.842541351,0.752812213,0.931861816,0.733078412,CS20,2.0,0.0,23.0,0.621923937,0.626984127,8.557664189,5.534092096,1.0,1.0,1.0
CY17,2025-04-17,0.923076923,NaN,NaN,0.960000000,0.928571429,1.000000000,0.962962963,1.000000000,1.000000000,0.980769231,1.000,NaN,NaN,0.913043478,0.947368421,NaN,0.882352941,0.750000000,0.357142857,0.674418605,-0.076923077,0.080610022,-0.157533099,NaN,0.250000000,NaN,NaN,0.642857143,NaN,0.046956522,0.306350626,-0.259394104,1.000000000,0.777777778,NaN,0.882352941,0.933333333,0.888888889,0.640000000,0.857142857,0.409090909,0.444444444,0.200000000,0.388888889,0.682926829,0.421052632,0.590909091,0.597560976,33.710983134,13.151605922,0.336451547,0.220394545,49.504035456,12.091954776,0.461485812,0.332273032,15.241142284,14.390858957,0.211417283,0.108516057,74.865217074,30.251087438,0.791579209,0.558174548,0.849773920,0.804557478,0.830056083,0.793389687,0.866722480,0.838265775,0.792273726,0.752014375,0.760705775,0.924517176,0.823841678,RL17,3.0,3.0,18.0,0.587423313,0.570469799,10.139517645,5.766086817,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RU10,2024-12-10,NaN,1.000000000,NaN,0.933333333,0.857142857,1.000000000,0.857142857,0.952380952,0.875000000,0.916666667,NaN,0.555555556,NaN,0.600000000,0.500000000,NaN,0.700000000,0.318181818,0.272727273,0.395348837,NaN,0.157142857,NaN,0.444444444,0.634199134,-0.189754690,NaN,0.602272727,NaN,0.333333333,0.521317829,-0.187984496,1.000000000,0.631578947,0.571428571,0.714285714,0.843750000,0.637931034,0.526315789,0.678899083,0.444444444,0.272727273,0.285714286,0.315789474,0.666666667,0.512820513,0.571428571,0.571428571,33.423653323,18.615019035,0.335884471,0.250472139,53.246734641,20.038486474,0.405781027,0.352966310,17.098762826,17.442751733,0.265987915,0.147977967,75.938950863,55.060336270,0.612756671,0.465079795,0.882619942,0.875157114,0.884644794,0.913986194,0.855303394,0.890747746,0.689337362,0.933808211,0.643281102,0.847687280,0.735393623,RK10,0.0,0.0,8.0,0.467372134,0.481481481,8.568536979,5.202948116,0.0,0.0,0.0
SH02,2025-04-02,0.956521739,0.928571429,0.888888889,0.934782609,0.956521739,0.913043478,0.875000000,0.750000000,1.000000000,0.891891892,0.950,NaN,0.714285714,0.794871795,0.750000000,0.842105263,0.250000000,0.076923077,0.181818182,0.166666667,0.006521739,0.625000000,-0.618478261,NaN,0.673076923,NaN,0.174603175,0.818181818,-0.643578644,0.139910814,0.725225225,-0.585314411,0.555555556,NaN,NaN,0.555555556,0.642857143,0.346153846,0.625000000,0.554347826,0.500000000,0.125000000,0.375000000,0.346153846,0.512820513,0.535714286,0.500000000,0.516853933,79.144418347,21.419024243,0.530238804,0.436898931,77.146477202,28.917666099,0.578339244,0.472166208,81.342153608,13.170518201,0.482138365,0.401631654,87.054086410,19.021758229,0.684610052,0.568817813,0.873133830,0.909790958,0.897269693,0.910452495,0.884086890,0.811004890,0.779562113,0.691967419,0.705998463,0.930042361,0.853125763,ML02,2.0,6.0,17.0,0.463414634,0.489510490,8.332132587,6.014491644,0.0,0.0,0.0
MC09,2025-05-09,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,0.857142857,0.714285714,0.736842105,1.000,0.857142857,0.900000000,0.916666667,0.833333333,1.000000000,0.533333333,0.375000000,NaN,0.517241379,0.000000000,NaN,NaN,0.142857143,0.482142857,-0.339285714,0.100000000,NaN,NaN,0.083333333,0.219600726,-0.136267393,0.718750000,0.571428571,0.681818182,0.676470588,0.666666667,0.578947368,0.714285714,0.663043478,0.685714286,0.571428571,0.695652174,0.666666667,0.444444444,0.600000000,0.444444444,0.468750000,29.478950211,13.145776948,0.291933950,0.220521447,61.857469295,18.940454888,0.442881002,0.354142654,0.000000000,7.870025391,0.140986897,0.086900239,7.144749197,9.025256722,0.145832569,0.113699580,0.813171808,0.831770102,0.861995768,0.806465390,0.917526147,0.837370946,0.773930916,0.784928306,0.782043796,0.889813586,0.765818036,AM09,2.0,5.0,16.0,0.618705036,0.620437956,9.049964221,7.013917900,0.0,0.0,1.0
VC20,2024-11-20,0.909090909,1.000000000,1.000000000,0.961538462,0.900000000,1.000000000,1.000000000,0.866666667,0.812500000,0.888888889,1.000,NaN,NaN,1.000000000,1.000000000,1.000000000,0.937500000,0.375000000,0.294117647,0.560975610,-0.090909091,0.062500000,-0.153409091,NaN,0.491666667,NaN,NaN,0.518382353,NaN,-0.038461538,0.327913279,-0.366374818,1.000000000,0.750000000,0.555555556,0.825000000,0.960784314,0.696969697,0.545454545,0.769230769,0.789473684,0.666666667,0.444444444,0.675000000,0.606060606,0.714285714,0.640000000,0.645569620,80.491537545,21.126056690,0.757716271,0.585180428,76.898542647,24.640118910,0.737009548,0.552731088,83.157307953,18.518849236,0.778422993,0.617629768,85.568614236,16.837282781,0.759785036,0.625746279,0.884698878,0.872315188,0.929941170,0.919642857,0.940239483,0.920729585,0.838854318,0.860664305,0.688576212,0.980794865,0.989132423,ZS20,3.0,4.0,17.0,0.703958692,0.669014085,9.932994786,6.675133394,0.0,0.0,0.0
PO03,2024-12-03,NaN,NaN,1.000000000,1.000000000,1.000000000,1.000000000,1.000000000,NaN,1.000000000,1.000000000,0.875,NaN,0.000000000,0.400000000,0.400000000,0.400000000,0.833333333,0.285714286,0.272727273,0.500000000,NaN,0.166666667,NaN,NaN,NaN,NaN,1.000000000,0.727272727,0.272727273,0.600000000,0.500000000,0.100000000,0.894736842,0.777777778,NaN,0.818181818,0.925000000,0.647058824,0.578947368,0.776315789,0.809523810,0.700000000,0.666666667,0.756756757,0.640000000,0.888888889,0.687500000,0.700000000,77.469864884,28.005587183,0.692054886,0.516104288,71.884195860,27.983910390,0.670039660,0.481468885,82.862924632,28.026516501,0.714070113,0.550739691,78.687626054,26.615758573,0.745038761,0.575511198,0.910460017,0.803740322,0.931348735,0.954132448,0.908565023,0.833358451,0.753918709,0.743994751,0.750826396,0.922722152,0.757011022,NN03,NaN,NaN,NaN,0.730582524,0.702970297,10.760837701,3.486404440,0.0,0.0,0.0