In [81]:
import sys
import os

sys.path.append('/Users/benny/Repos/octagon_analysis')

In [82]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import parse_data.prepare_data as prepare_data
import parse_data.identify_filepaths as identify_filepaths
import trait_analyses.functions.prepare_questionnaire_data as prepare_questionnaire_data
import globals

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [83]:
data_folder = '/Volumes/ogma/human_octagon/RAW/standard'
#personal_data_csv = '/Users/benny/Desktop/MSc/Project/Git/repos/main_copy/questionnaire_analysis/questionnaire_data/personal_data.csv'

In [84]:
social_files, ordered_solos = identify_filepaths.get_filenames(data_folder=data_folder)

In [85]:
first_solos = ordered_solos[::2]
second_solos = ordered_solos[1::2]

# Load data

In [86]:
df_socials, social_lists = prepare_data.prepare_data(data_folder, social_files, combine=False)

IntProgress(value=0, max=101)

filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-31-00_YW13_JL13_Social.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-25-20_SH27_EN27_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-28-40_SP17_AW17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_16-41-38_ZH17_EM17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-31-14_KA12_WM12_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-23-24_FA12_SL12_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-18-54_NK13_RD13_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-28-07_YL13_HC13_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-24-49_AV19_XG19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-22-56_SB19_HH19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-17-44_JS20_RR20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-16-21_ZS20_VC20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-31-51_PO03_NN03_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-27-28_EX03_BC03_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-21-17_TE10_TK10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-20-11_RK10_RU10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-28-24_JU19_SY19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_17-44-50_KS20_CS20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-21-27_YY15_MR15_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-27-23_YL15_RR15_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_17-11-07_DB04_GG04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-12-57_KC14_WL14_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_13-10-49_AE14_JL14_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-24-05_MA14_RM14_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-22-29_SJ18_CD18_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-22-17_JK18_HL18_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-27-32_HM18_SC18_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-29-40_HL19_AW19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-33-16_PT19_JL19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-27-01_IS01_HQ01_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-29-49_AL01_NL01_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-26-25_SH02_ML02_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-31-29_JW04_JI04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-29-00_AR10_MY10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250411_1/2025-04-11_09-29-35_IN11_CW11_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250417_1/2025-04-17_12-22-26_CY17_RL17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_1/2025-04-21_09-29-53_NM21_KC21_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_2/2025-04-21_10-29-08_LM21_LS21_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250502_1/2025-05-02_11-21-38_JC02_KS02_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250509_1/2025-05-09_12-30-13_AM09_MC09_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_1/2025-05-12_09-35-29_TG12_SC12_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_2/2025-05-12_12-23-08_NO12_AS12_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250520_1/2025-05-20_14-29-04_CY20_MJ20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250521_1/2025-05-21_09-31-42_EH21_SP21_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250522_1/2025-05-22_09-26-39_SS22_AD22_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250523_1/2025-05-23_18-05-58_JW23_YL23_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250524_1/2025-05-24_10-28-19_JP24_IP24_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250530_1/2025-05-30_11-33-24_ZZ30_VW30_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250604_1/2025-06-04_15-23-18_MP04_SH04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250620_1/2025-06-20_15-30-03_JK20_DD20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251003_1/2025-10-03_12-27-43_SI03_YL03_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_1/2025-10-10_10-20-12_AP10_CZ10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_2/2025-10-10_11-26-39_ES10_NM10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_3/2025-10-10_14-38-30_HT10_WT10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_4/2025-10-10_15-36-50_YL10_NO10_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-23-15_FA13_HW13_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-27-33_SW13_MU13_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251015_1/2025-10-15_09-21-08_CS15_SK15_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_1/2025-10-17_10-28-49_XL17_EV17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_2/2025-10-17_11-28-45_MZ17_CW17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_1/2025-11-03_13-29-01_TG03_HW03_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_2/2025-11-03_16-25-25_YG03_XA03_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251104_1/2025-11-04_13-29-35_UL04_MV04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251105_1/2025-11-05_14-30-16_ZO05_CL05_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251120_1/2025-11-20_10-34-37_NH20_MA20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251215_1/2025-12-15_11-36-00_CK15_AM15_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_1/2025-12-19_13-06-21_PE19_AT19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_2/2025-12-19_14-05-09_NJ19_BL19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260107_1/2026-01-07_10-29-12_AF07_AC07_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260109_1/2026-01-09_10-30-19_DM09_FB09_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260109_2/2026-01-09_11-31-23_IM09_KM09_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260114_1/2026-01-14_13-58-50_CG14_JD14_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260116_1/2026-01-16_14-32-42_EL16_FR16_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260120_1/2026-01-20_12-32-17_RA20_AM20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260120_2/2026-01-20_13-41-20_LW20_SG20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260120_3/2026-01-20_14-37-11_HH20_KH20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260121_1/2026-01-21_13-26-16_ZC21_JX21_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260128_1/2026-01-28_12-38-52_OK28_DP28_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260128_2/2026-01-28_13-36-39_YG28_GN28_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260130_1/2026-01-30_17-28-15_ZT30_SW30_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260202_1/2026-02-02_13-21-34_KF02_KE02_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260204_1/2026-02-04_13-33-21_YL04_LY04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260205_1/2026-02-05_13-28-49_MO05_IP05_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260209_1/2026-02-09_17-22-31_KW09_BR09_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260209_2/2026-02-09_18-23-58_YS09_ZX09_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260213_1/2026-02-13_13-21-41_NA13_EK13_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260216_1/2026-02-16_09-30-29_MP16_JS16_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260218_1/2026-02-18_17-24-31_AJ18_LZ18_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260219_1/2026-02-19_14-51-40_NB19_AS19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260220_1/2026-02-20_11-26-20_SS20_YL20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260220_2/2026-02-20_16-28-01_KR20_PJ20_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260304_1/2026-03-04_13-19-56_RL04_AK04_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260306_1/2026-03-06_13-35-23_AT06_AK06_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260306_2/2026-03-06_15-21-47_ZB06_LS06_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260309_1/2026-03-09_14-28-38_NC09_EE09_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260317_1/2026-03-17_15-26-15_AS17_QC17_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260319_1/2026-03-19_11-59-06_JP19_LM19_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260323_1/2026-03-23_11-29-22_SL23_KF23_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260327_1/2026-03-27_11-21-07_MI27_YZ27_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260327_2/2026-03-27_14-25-44_DT27_RW27_Social.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260330_1/2026-03-30_15-32-12_JJ30_NC30_Social.json
Loading complete.
Preprocessing complete.

In [87]:
df_solos, solos_lists = prepare_data.prepare_data(data_folder, ordered_solos, combine=False)

IntProgress(value=0, max=404)

filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-23-37_YW13_FirstSolo.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-53-34_YW13_SecondSolo.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-23-50_JL13_FirstSolo.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-53-56_JL13_SecondSolo.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-14-31_SH27_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-45-55_SH27_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-14-42_EN27_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-45-46_EN27_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-20-28_SP17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-50-03_SP17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-20-50_AW17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-51-22_AW17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_16-36-05_ZH17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_17-11-46_ZH17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_16-35-45_EM17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_17-12-29_EM17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-19-22_KA12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-50-23_KA12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-18-59_WM12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-50-20_WM12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-13-34_FA12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-44-54_FA12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-11-45_SL12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-45-35_SL12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-12-43_NK13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-37-06_NK13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-12-41_RD13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-37-20_RD13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-22-20_YL13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-51-39_YL13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-21-50_HC13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-51-16_HC13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-18-18_AV19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-44-00_AV19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-18-44_XG19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-44-31_XG19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-15-53_SB19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-47-53_SB19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-14-19_HH19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-47-29_HH19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-12-06_JS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-42-16_JS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-12-33_RR20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-41-56_RR20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-10-00_ZS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-40-08_ZS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-10-17_VC20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-39-49_VC20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-20-13_PO03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-52-05_PO03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-19-21_NN03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-52-30_NN03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-19-51_EX03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-53-11_EX03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-20-09_BC03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-52-57_BC03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-13-47_TE10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-45-41_TE10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-12-58_TK10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-45-09_TK10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-12-18_RK10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-42-27_RK10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-11-46_RU10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-41-53_RU10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-20-18_JU19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-51-58_JU19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-22-13_SY19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-51-33_SY19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_17-36-27_KS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_18-06-10_KS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_17-36-54_CS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_18-06-44_CS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-12-13_YY15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-47-11_YY15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-12-39_MR15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-46-04_MR15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-14-40_YL15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-50-13_YL15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-14-58_RR15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-50-37_RR15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_16-58-53_DB04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_17-32-55_DB04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_16-58-37_GG04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_17-33-22_GG04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-03-08_KC14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-36-26_KC14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-03-22_WL14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-35-54_WL14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_12-59-24_AE14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_13-32-14_AE14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_12-59-36_JL14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_13-32-33_JL14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-12-29_MA14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-46-57_MA14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-12-49_RM14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-46-27_RM14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-09-51_SJ18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-44-19_SJ18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-10-34_CD18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-44-40_CD18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-10-59_JK18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-44-49_JK18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-11-11_HL18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-45-29_HL18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-15-58_HM18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-48-42_HM18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-16-10_SC18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-49-19_SC18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-17-55_HL19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-51-16_HL19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-17-46_AW19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-51-26_AW19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-22-02_PT19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-54-33_PT19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-22-13_JL19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-55-00_JL19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-15-29_IS01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-48-25_IS01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-15-24_HQ01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-48-51_HQ01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-17-03_AL01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-52-21_AL01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-17-26_NL01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-52-54_NL01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-13-59_SH02_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-48-31_SH02_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-14-13_ML02_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-48-09_ML02_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-18-59_JW04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-53-32_JW04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-19-11_JI04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-53-11_JI04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-16-12_AR10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-53-58_AR10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-16-26_MY10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-53-34_MY10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250411_1/2025-04-11_09-17-58_IN11_FirstSolo.json
Loading complete.
Preprocessing complete.

In [88]:
df_first_solos, first_solos_lists = prepare_data.prepare_data(data_folder, first_solos, combine=False)
df_second_solos, second_solos_lists = prepare_data.prepare_data(data_folder, second_solos, combine=False)

IntProgress(value=0, max=202)

filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-23-37_YW13_FirstSolo.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-23-50_JL13_FirstSolo.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-14-31_SH27_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-14-42_EN27_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-20-28_SP17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-20-50_AW17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_16-36-05_ZH17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_16-35-45_EM17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-19-22_KA12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-18-59_WM12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-13-34_FA12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-11-45_SL12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-12-43_NK13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-12-41_RD13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-22-20_YL13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-21-50_HC13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-18-18_AV19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-18-44_XG19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-15-53_SB19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-14-19_HH19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-12-06_JS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-12-33_RR20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-10-00_ZS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-10-17_VC20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-20-13_PO03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-19-21_NN03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-19-51_EX03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-20-09_BC03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-13-47_TE10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-12-58_TK10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-12-18_RK10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-11-46_RU10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-20-18_JU19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-22-13_SY19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_17-36-27_KS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_17-36-54_CS20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-12-13_YY15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-12-39_MR15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-14-40_YL15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-14-58_RR15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_16-58-53_DB04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_16-58-37_GG04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-03-08_KC14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-03-22_WL14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_12-59-24_AE14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_12-59-36_JL14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-12-29_MA14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-12-49_RM14_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-09-51_SJ18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-10-34_CD18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-10-59_JK18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-11-11_HL18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-15-58_HM18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-16-10_SC18_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-17-55_HL19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-17-46_AW19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-22-02_PT19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-22-13_JL19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-15-29_IS01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-15-24_HQ01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-17-03_AL01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-17-26_NL01_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-13-59_SH02_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-14-13_ML02_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-18-59_JW04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-19-11_JI04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-16-12_AR10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-16-26_MY10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250411_1/2025-04-11_09-17-58_IN11_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250411_1/2025-04-11_09-18-11_CW11_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250417_1/2025-04-17_12-09-51_CY17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250417_1/2025-04-17_12-10-56_RL17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_1/2025-04-21_09-18-28_NM21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_1/2025-04-21_09-18-42_KC21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_2/2025-04-21_10-18-48_LM21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_2/2025-04-21_10-18-58_LS21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250502_1/2025-05-02_11-09-55_JC02_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250502_1/2025-05-02_11-10-14_KS02_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250509_1/2025-05-09_12-18-03_AM09_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250509_1/2025-05-09_12-18-53_MC09_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_1/2025-05-12_09-24-24_TG12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_1/2025-05-12_09-24-39_SC12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_2/2025-05-12_12-10-42_NO12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_2/2025-05-12_12-10-18_AS12_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250520_1/2025-05-20_14-15-25_CY20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250520_1/2025-05-20_14-15-00_MJ20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250521_1/2025-05-21_09-21-15_EH21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250521_1/2025-05-21_09-21-16_SP21_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250522_1/2025-05-22_09-15-24_SS22_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250522_1/2025-05-22_09-15-49_AD22_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250523_1/2025-05-23_17-54-31_JW23_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250523_1/2025-05-23_17-54-43_YL23_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250524_1/2025-05-24_10-16-54_JP24_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250524_1/2025-05-24_10-17-04_IP24_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250530_1/2025-05-30_11-18-37_ZZ30_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250530_1/2025-05-30_11-18-19_VW30_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250604_1/2025-06-04_15-11-03_MP04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250604_1/2025-06-04_15-11-26_SH04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250620_1/2025-06-20_15-18-58_JK20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250620_1/2025-06-20_15-19-07_DD20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251003_1/2025-10-03_12-15-34_SI03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251003_1/2025-10-03_12-14-36_YL03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_1/2025-10-10_10-08-29_AP10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_1/2025-10-10_10-08-13_CZ10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_2/2025-10-10_11-15-39_ES10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_2/2025-10-10_11-15-28_NM10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_3/2025-10-10_14-28-00_HT10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_3/2025-10-10_14-27-52_WT10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_4/2025-10-10_15-28-22_YL10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_4/2025-10-10_15-28-37_NO10_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-13-04_FA13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-12-53_HW13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-16-45_SW13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-16-36_MU13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251015_1/2025-10-15_09-10-38_CS15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251015_1/2025-10-15_09-10-52_SK15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_1/2025-10-17_10-16-46_XL17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_1/2025-10-17_10-17-01_EV17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_2/2025-10-17_11-18-32_MZ17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_2/2025-10-17_11-18-44_CW17_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_1/2025-11-03_13-18-16_TG03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_1/2025-11-03_13-17-59_HW03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_2/2025-11-03_16-13-23_YG03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_2/2025-11-03_16-13-02_XA03_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251104_1/2025-11-04_13-18-40_UL04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251104_1/2025-11-04_13-18-58_MV04_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251105_1/2025-11-05_14-16-53_ZO05_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251105_1/2025-11-05_14-16-20_CL05_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251120_1/2025-11-20_10-21-38_NH20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251120_1/2025-11-20_10-21-21_MA20_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251215_1/2025-12-15_11-22-45_CK15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251215_1/2025-12-15_11-23-02_AM15_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_1/2025-12-19_12-55-14_PE19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_1/2025-12-19_12-54-54_AT19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_2/2025-12-19_13-53-59_NJ19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_2/2025-12-19_13-54-13_BL19_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260107_1/2026-01-07_10-17-45_AF07_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260107_1/2026-01-07_10-17-37_AC07_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260109_1/2026-01-09_10-17-52_DM09_FirstSolo.json
Loading complete.
Preprocessing complete.

IntProgress(value=0, max=202)

filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-53-34_YW13_SecondSolo.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240913_1/2024-09-13_11-53-56_JL13_SecondSolo.json
Data is from period before 2024-09-13 00:00:00
Running dataframe through playerinfo_playerposition_conversion.
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-45-55_SH27_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/240927_1/2024-09-27_14-45-46_EN27_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-50-03_SP17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_1/2024-10-17_14-51-22_AW17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_17-11-46_ZH17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241017_2/2024-10-17_17-12-29_EM17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-50-23_KA12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_1/2024-11-12_13-50-20_WM12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-44-54_FA12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241112_2/2024-11-12_15-45-35_SL12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-37-06_NK13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_1/2024-11-13_14-37-20_RD13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-51-39_YL13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241113_2/2024-11-13_15-51-16_HC13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-44-00_AV19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_1/2024-11-19_14-44-31_XG19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-47-53_SB19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241119_2/2024-11-19_15-47-29_HH19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-42-16_JS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_1/2024-11-20_14-41-56_RR20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-40-08_ZS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241120_2/2024-11-20_15-39-49_VC20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-52-05_PO03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_1/2024-12-03_14-52-30_NN03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-53-11_EX03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241203_2/2024-12-03_15-52-57_BC03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-45-41_TE10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_1/2024-12-10_14-45-09_TK10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-42-27_RK10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241210_2/2024-12-10_15-41-53_RU10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-51-58_JU19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241219_1/2024-12-19_15-51-33_SY19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_18-06-10_KS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/241220_1/2024-12-20_18-06-44_CS20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-47-11_YY15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_1/2025-01-15_15-46-04_MR15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-50-13_YL15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250115_2/2025-01-15_16-50-37_RR15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_17-32-55_DB04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250204_2/2025-02-04_17-33-22_GG04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-36-26_KC14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_1/2025-03-14_12-35-54_WL14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_13-32-14_AE14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_2/2025-03-14_13-32-33_JL14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-46-57_MA14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250314_3/2025-03-14_14-46-27_RM14_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-44-19_SJ18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_1/2025-03-18_14-44-40_CD18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-44-49_JK18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_2/2025-03-18_16-45-29_HL18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-48-42_HM18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250318_3/2025-03-18_17-49-19_SC18_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-51-16_HL19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_1/2025-03-19_13-51-26_AW19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-54-33_PT19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250319_2/2025-03-19_14-55-00_JL19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-48-25_IS01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_1/2025-04-01_14-48-51_HQ01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-52-21_AL01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250401_2/2025-04-01_15-52-54_NL01_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-48-31_SH02_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250402_1/2025-04-02_16-48-09_ML02_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-53-32_JW04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250404_1/2025-04-04_10-53-11_JI04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-53-58_AR10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250410_1/2025-04-10_12-53-34_MY10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250411_1/2025-04-11_09-51-07_IN11_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250411_1/2025-04-11_09-51-19_CW11_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250417_1/2025-04-17_12-46-27_CY17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250417_1/2025-04-17_12-46-05_RL17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_1/2025-04-21_09-51-36_NM21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_1/2025-04-21_09-51-56_KC21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_2/2025-04-21_10-50-34_LM21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250421_2/2025-04-21_10-50-54_LS21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250502_1/2025-05-02_11-44-02_JC02_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250502_1/2025-05-02_11-43-42_KS02_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250509_1/2025-05-09_12-53-10_AM09_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250509_1/2025-05-09_12-53-00_MC09_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_1/2025-05-12_09-58-02_TG12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_1/2025-05-12_09-57-44_SC12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_2/2025-05-12_12-44-45_NO12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250512_2/2025-05-12_12-45-03_AS12_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250520_1/2025-05-20_14-53-46_CY20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250520_1/2025-05-20_14-53-15_MJ20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250521_1/2025-05-21_09-55-07_EH21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250521_1/2025-05-21_09-55-08_SP21_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250522_1/2025-05-22_09-49-04_SS22_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250522_1/2025-05-22_09-49-03_AD22_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250523_1/2025-05-23_18-27-58_JW23_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250523_1/2025-05-23_18-27-42_YL23_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250524_1/2025-05-24_10-53-00_JP24_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250524_1/2025-05-24_10-52-48_IP24_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250530_1/2025-05-30_11-57-32_ZZ30_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250530_1/2025-05-30_11-56-49_VW30_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250604_1/2025-06-04_15-46-01_MP04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250604_1/2025-06-04_15-45-49_SH04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250620_1/2025-06-20_15-51-01_JK20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/250620_1/2025-06-20_15-50-46_DD20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251003_1/2025-10-03_12-52-54_SI03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251003_1/2025-10-03_12-52-19_YL03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_1/2025-10-10_10-41-41_AP10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_1/2025-10-10_10-42-01_CZ10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_2/2025-10-10_11-48-35_ES10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_2/2025-10-10_11-48-28_NM10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_3/2025-10-10_15-00-24_HT10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_3/2025-10-10_15-00-35_WT10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_4/2025-10-10_15-58-20_YL10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251010_4/2025-10-10_15-58-29_NO10_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-44-03_FA13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-44-12_HW13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-45-48_SW13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-45-03_MU13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251015_1/2025-10-15_09-42-32_CS15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251015_1/2025-10-15_09-42-45_SK15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_1/2025-10-17_10-51-05_XL17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_1/2025-10-17_10-50-57_EV17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_2/2025-10-17_11-50-05_MZ17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251017_2/2025-10-17_11-50-15_CW17_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_1/2025-11-03_13-51-23_TG03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_1/2025-11-03_13-51-34_HW03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_2/2025-11-03_16-47-32_YG03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251103_2/2025-11-03_16-47-45_XA03_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251104_1/2025-11-04_13-49-59_UL04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251104_1/2025-11-04_13-50-13_MV04_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251105_1/2025-11-05_14-52-43_ZO05_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251105_1/2025-11-05_14-52-33_CL05_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251120_1/2025-11-20_10-57-11_NH20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251120_1/2025-11-20_10-56-50_MA20_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251215_1/2025-12-15_11-56-34_CK15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251215_1/2025-12-15_11-56-13_AM15_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_1/2025-12-19_13-28-00_PE19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_1/2025-12-19_13-27-38_AT19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_2/2025-12-19_14-42-48_NJ19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/251219_2/2025-12-19_14-31-09_BL19_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260107_1/2026-01-07_10-50-50_AF07_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /Volumes/ogma/human_octagon/RAW/standard/260107_1/2026-01-07_10-50-33_AC07_SecondSolo.json
Loading complete.
Preprocessing complete.

In [89]:
# combined solos
combined_solos = []

for trial_list_idx in range(0, len(solos_lists), 2):

    print(ordered_solos[trial_list_idx], ordered_solos[trial_list_idx + 1]) 

    # concatenate the trial lists for the 2 solos of this session
    trial_list_combined = solos_lists[trial_list_idx] + solos_lists[trial_list_idx + 1]

    combined_solos.append(trial_list_combined)

240913_1/2024-09-13_11-23-37_YW13_FirstSolo.json 240913_1/2024-09-13_11-53-34_YW13_SecondSolo.json
240913_1/2024-09-13_11-23-50_JL13_FirstSolo.json 240913_1/2024-09-13_11-53-56_JL13_SecondSolo.json
240927_1/2024-09-27_14-14-31_SH27_FirstSolo.json 240927_1/2024-09-27_14-45-55_SH27_SecondSolo.json
240927_1/2024-09-27_14-14-42_EN27_FirstSolo.json 240927_1/2024-09-27_14-45-46_EN27_SecondSolo.json
241017_1/2024-10-17_14-20-28_SP17_FirstSolo.json 241017_1/2024-10-17_14-50-03_SP17_SecondSolo.json
241017_1/2024-10-17_14-20-50_AW17_FirstSolo.json 241017_1/2024-10-17_14-51-22_AW17_SecondSolo.json
241017_2/2024-10-17_16-36-05_ZH17_FirstSolo.json 241017_2/2024-10-17_17-11-46_ZH17_SecondSolo.json
241017_2/2024-10-17_16-35-45_EM17_FirstSolo.json 241017_2/2024-10-17_17-12-29_EM17_SecondSolo.json
241112_1/2024-11-12_13-19-22_KA12_FirstSolo.json 241112_1/2024-11-12_13-50-23_KA12_SecondSolo.json
241112_1/2024-11-12_13-18-59_WM12_FirstSolo.json 241112_1/2024-11-12_13-50-20_WM12_SecondSolo.json
241112_2/2024-11-12_15-13-34_FA12_FirstSolo.json 241112_2/2024-11-12_15-44-54_FA12_SecondSolo.json
241112_2/2024-11-12_15-11-45_SL12_FirstSolo.json 241112_2/2024-11-12_15-45-35_SL12_SecondSolo.json
241113_1/2024-11-13_14-12-43_NK13_FirstSolo.json 241113_1/2024-11-13_14-37-06_NK13_SecondSolo.json
241113_1/2024-11-13_14-12-41_RD13_FirstSolo.json 241113_1/2024-11-13_14-37-20_RD13_SecondSolo.json
241113_2/2024-11-13_15-22-20_YL13_FirstSolo.json 241113_2/2024-11-13_15-51-39_YL13_SecondSolo.json
241113_2/2024-11-13_15-21-50_HC13_FirstSolo.json 241113_2/2024-11-13_15-51-16_HC13_SecondSolo.json
241119_1/2024-11-19_14-18-18_AV19_FirstSolo.json 241119_1/2024-11-19_14-44-00_AV19_SecondSolo.json
241119_1/2024-11-19_14-18-44_XG19_FirstSolo.json 241119_1/2024-11-19_14-44-31_XG19_SecondSolo.json
241119_2/2024-11-19_15-15-53_SB19_FirstSolo.json 241119_2/2024-11-19_15-47-53_SB19_SecondSolo.json
241119_2/2024-11-19_15-14-19_HH19_FirstSolo.json 241119_2/2024-11-19_15-47-29_HH19_SecondSolo.json
241120_1/2024-11-20_14-12-06_JS20_FirstSolo.json 241120_1/2024-11-20_14-42-16_JS20_SecondSolo.json
241120_1/2024-11-20_14-12-33_RR20_FirstSolo.json 241120_1/2024-11-20_14-41-56_RR20_SecondSolo.json
241120_2/2024-11-20_15-10-00_ZS20_FirstSolo.json 241120_2/2024-11-20_15-40-08_ZS20_SecondSolo.json
241120_2/2024-11-20_15-10-17_VC20_FirstSolo.json 241120_2/2024-11-20_15-39-49_VC20_SecondSolo.json
241203_1/2024-12-03_14-20-13_PO03_FirstSolo.json 241203_1/2024-12-03_14-52-05_PO03_SecondSolo.json
241203_1/2024-12-03_14-19-21_NN03_FirstSolo.json 241203_1/2024-12-03_14-52-30_NN03_SecondSolo.json
241203_2/2024-12-03_15-19-51_EX03_FirstSolo.json 241203_2/2024-12-03_15-53-11_EX03_SecondSolo.json
241203_2/2024-12-03_15-20-09_BC03_FirstSolo.json 241203_2/2024-12-03_15-52-57_BC03_SecondSolo.json
241210_1/2024-12-10_14-13-47_TE10_FirstSolo.json 241210_1/2024-12-10_14-45-41_TE10_SecondSolo.json
241210_1/2024-12-10_14-12-58_TK10_FirstSolo.json 241210_1/2024-12-10_14-45-09_TK10_SecondSolo.json
241210_2/2024-12-10_15-12-18_RK10_FirstSolo.json 241210_2/2024-12-10_15-42-27_RK10_SecondSolo.json
241210_2/2024-12-10_15-11-46_RU10_FirstSolo.json 241210_2/2024-12-10_15-41-53_RU10_SecondSolo.json
241219_1/2024-12-19_15-20-18_JU19_FirstSolo.json 241219_1/2024-12-19_15-51-58_JU19_SecondSolo.json
241219_1/2024-12-19_15-22-13_SY19_FirstSolo.json 241219_1/2024-12-19_15-51-33_SY19_SecondSolo.json
241220_1/2024-12-20_17-36-27_KS20_FirstSolo.json 241220_1/2024-12-20_18-06-10_KS20_SecondSolo.json
241220_1/2024-12-20_17-36-54_CS20_FirstSolo.json 241220_1/2024-12-20_18-06-44_CS20_SecondSolo.json
250115_1/2025-01-15_15-12-13_YY15_FirstSolo.json 250115_1/2025-01-15_15-47-11_YY15_SecondSolo.json
250115_1/2025-01-15_15-12-39_MR15_FirstSolo.json 250115_1/2025-01-15_15-46-04_MR15_SecondSolo.json
250115_2/2025-01-15_16-14-40_YL15_FirstSolo.json 250115_2/2025-01-15_16-50-13_YL15_SecondSolo.json
250115_2/2025-01-15_16-14-58_RR15_FirstSolo.json 250115_2/2025-01-15_16-50-37_RR15_SecondSolo.json
250204_2/2025-02-04_16-58-53_DB04_FirstSolo.json 250204_2/2025-02-04_17-32-55_DB04_SecondSolo.json
250204_2/2025-02-04_16-58-37_GG04_FirstSolo.json 250204_2/2025-02-04_17-33-22_GG04_SecondSolo.json
250314_1/2025-03-14_12-03-08_KC14_FirstSolo.json 250314_1/2025-03-14_12-36-26_KC14_SecondSolo.json
250314_1/2025-03-14_12-03-22_WL14_FirstSolo.json 250314_1/2025-03-14_12-35-54_WL14_SecondSolo.json
250314_2/2025-03-14_12-59-24_AE14_FirstSolo.json 250314_2/2025-03-14_13-32-14_AE14_SecondSolo.json
250314_2/2025-03-14_12-59-36_JL14_FirstSolo.json 250314_2/2025-03-14_13-32-33_JL14_SecondSolo.json
250314_3/2025-03-14_14-12-29_MA14_FirstSolo.json 250314_3/2025-03-14_14-46-57_MA14_SecondSolo.json
250314_3/2025-03-14_14-12-49_RM14_FirstSolo.json 250314_3/2025-03-14_14-46-27_RM14_SecondSolo.json
250318_1/2025-03-18_14-09-51_SJ18_FirstSolo.json 250318_1/2025-03-18_14-44-19_SJ18_SecondSolo.json
250318_1/2025-03-18_14-10-34_CD18_FirstSolo.json 250318_1/2025-03-18_14-44-40_CD18_SecondSolo.json
250318_2/2025-03-18_16-10-59_JK18_FirstSolo.json 250318_2/2025-03-18_16-44-49_JK18_SecondSolo.json
250318_2/2025-03-18_16-11-11_HL18_FirstSolo.json 250318_2/2025-03-18_16-45-29_HL18_SecondSolo.json
250318_3/2025-03-18_17-15-58_HM18_FirstSolo.json 250318_3/2025-03-18_17-48-42_HM18_SecondSolo.json
250318_3/2025-03-18_17-16-10_SC18_FirstSolo.json 250318_3/2025-03-18_17-49-19_SC18_SecondSolo.json
250319_1/2025-03-19_13-17-55_HL19_FirstSolo.json 250319_1/2025-03-19_13-51-16_HL19_SecondSolo.json
250319_1/2025-03-19_13-17-46_AW19_FirstSolo.json 250319_1/2025-03-19_13-51-26_AW19_SecondSolo.json
250319_2/2025-03-19_14-22-02_PT19_FirstSolo.json 250319_2/2025-03-19_14-54-33_PT19_SecondSolo.json
250319_2/2025-03-19_14-22-13_JL19_FirstSolo.json 250319_2/2025-03-19_14-55-00_JL19_SecondSolo.json
250401_1/2025-04-01_14-15-29_IS01_FirstSolo.json 250401_1/2025-04-01_14-48-25_IS01_SecondSolo.json
250401_1/2025-04-01_14-15-24_HQ01_FirstSolo.json 250401_1/2025-04-01_14-48-51_HQ01_SecondSolo.json
250401_2/2025-04-01_15-17-03_AL01_FirstSolo.json 250401_2/2025-04-01_15-52-21_AL01_SecondSolo.json
250401_2/2025-04-01_15-17-26_NL01_FirstSolo.json 250401_2/2025-04-01_15-52-54_NL01_SecondSolo.json
250402_1/2025-04-02_16-13-59_SH02_FirstSolo.json 250402_1/2025-04-02_16-48-31_SH02_SecondSolo.json
250402_1/2025-04-02_16-14-13_ML02_FirstSolo.json 250402_1/2025-04-02_16-48-09_ML02_SecondSolo.json
250404_1/2025-04-04_10-18-59_JW04_FirstSolo.json 250404_1/2025-04-04_10-53-32_JW04_SecondSolo.json
250404_1/2025-04-04_10-19-11_JI04_FirstSolo.json 250404_1/2025-04-04_10-53-11_JI04_SecondSolo.json
250410_1/2025-04-10_12-16-12_AR10_FirstSolo.json 250410_1/2025-04-10_12-53-58_AR10_SecondSolo.json
250410_1/2025-04-10_12-16-26_MY10_FirstSolo.json 250410_1/2025-04-10_12-53-34_MY10_SecondSolo.json
250411_1/2025-04-11_09-17-58_IN11_FirstSolo.json 250411_1/2025-04-11_09-51-07_IN11_SecondSolo.json
250411_1/2025-04-11_09-18-11_CW11_FirstSolo.json 250411_1/2025-04-11_09-51-19_CW11_SecondSolo.json
250417_1/2025-04-17_12-09-51_CY17_FirstSolo.json 250417_1/2025-04-17_12-46-27_CY17_SecondSolo.json
250417_1/2025-04-17_12-10-56_RL17_FirstSolo.json 250417_1/2025-04-17_12-46-05_RL17_SecondSolo.json
250421_1/2025-04-21_09-18-28_NM21_FirstSolo.json 250421_1/2025-04-21_09-51-36_NM21_SecondSolo.json
250421_1/2025-04-21_09-18-42_KC21_FirstSolo.json 250421_1/2025-04-21_09-51-56_KC21_SecondSolo.json
250421_2/2025-04-21_10-18-48_LM21_FirstSolo.json 250421_2/2025-04-21_10-50-34_LM21_SecondSolo.json
250421_2/2025-04-21_10-18-58_LS21_FirstSolo.json 250421_2/2025-04-21_10-50-54_LS21_SecondSolo.json
250502_1/2025-05-02_11-09-55_JC02_FirstSolo.json 250502_1/2025-05-02_11-44-02_JC02_SecondSolo.json
250502_1/2025-05-02_11-10-14_KS02_FirstSolo.json 250502_1/2025-05-02_11-43-42_KS02_SecondSolo.json
250509_1/2025-05-09_12-18-03_AM09_FirstSolo.json 250509_1/2025-05-09_12-53-10_AM09_SecondSolo.json
250509_1/2025-05-09_12-18-53_MC09_FirstSolo.json 250509_1/2025-05-09_12-53-00_MC09_SecondSolo.json
250512_1/2025-05-12_09-24-24_TG12_FirstSolo.json 250512_1/2025-05-12_09-58-02_TG12_SecondSolo.json
250512_1/2025-05-12_09-24-39_SC12_FirstSolo.json 250512_1/2025-05-12_09-57-44_SC12_SecondSolo.json
250512_2/2025-05-12_12-10-42_NO12_FirstSolo.json 250512_2/2025-05-12_12-44-45_NO12_SecondSolo.json
250512_2/2025-05-12_12-10-18_AS12_FirstSolo.json 250512_2/2025-05-12_12-45-03_AS12_SecondSolo.json
250520_1/2025-05-20_14-15-25_CY20_FirstSolo.json 250520_1/2025-05-20_14-53-46_CY20_SecondSolo.json
250520_1/2025-05-20_14-15-00_MJ20_FirstSolo.json 250520_1/2025-05-20_14-53-15_MJ20_SecondSolo.json
250521_1/2025-05-21_09-21-15_EH21_FirstSolo.json 250521_1/2025-05-21_09-55-07_EH21_SecondSolo.json
250521_1/2025-05-21_09-21-16_SP21_FirstSolo.json 250521_1/2025-05-21_09-55-08_SP21_SecondSolo.json
250522_1/2025-05-22_09-15-24_SS22_FirstSolo.json 250522_1/2025-05-22_09-49-04_SS22_SecondSolo.json
250522_1/2025-05-22_09-15-49_AD22_FirstSolo.json 250522_1/2025-05-22_09-49-03_AD22_SecondSolo.json
250523_1/2025-05-23_17-54-31_JW23_FirstSolo.json 250523_1/2025-05-23_18-27-58_JW23_SecondSolo.json
250523_1/2025-05-23_17-54-43_YL23_FirstSolo.json 250523_1/2025-05-23_18-27-42_YL23_SecondSolo.json
250524_1/2025-05-24_10-16-54_JP24_FirstSolo.json 250524_1/2025-05-24_10-53-00_JP24_SecondSolo.json
250524_1/2025-05-24_10-17-04_IP24_FirstSolo.json 250524_1/2025-05-24_10-52-48_IP24_SecondSolo.json
250530_1/2025-05-30_11-18-37_ZZ30_FirstSolo.json 250530_1/2025-05-30_11-57-32_ZZ30_SecondSolo.json
250530_1/2025-05-30_11-18-19_VW30_FirstSolo.json 250530_1/2025-05-30_11-56-49_VW30_SecondSolo.json
250604_1/2025-06-04_15-11-03_MP04_FirstSolo.json 250604_1/2025-06-04_15-46-01_MP04_SecondSolo.json
250604_1/2025-06-04_15-11-26_SH04_FirstSolo.json 250604_1/2025-06-04_15-45-49_SH04_SecondSolo.json
250620_1/2025-06-20_15-18-58_JK20_FirstSolo.json 250620_1/2025-06-20_15-51-01_JK20_SecondSolo.json
250620_1/2025-06-20_15-19-07_DD20_FirstSolo.json 250620_1/2025-06-20_15-50-46_DD20_SecondSolo.json
251003_1/2025-10-03_12-15-34_SI03_FirstSolo.json 251003_1/2025-10-03_12-52-54_SI03_SecondSolo.json
251003_1/2025-10-03_12-14-36_YL03_FirstSolo.json 251003_1/2025-10-03_12-52-19_YL03_SecondSolo.json
251010_1/2025-10-10_10-08-29_AP10_FirstSolo.json 251010_1/2025-10-10_10-41-41_AP10_SecondSolo.json
251010_1/2025-10-10_10-08-13_CZ10_FirstSolo.json 251010_1/2025-10-10_10-42-01_CZ10_SecondSolo.json
251010_2/2025-10-10_11-15-39_ES10_FirstSolo.json 251010_2/2025-10-10_11-48-35_ES10_SecondSolo.json
251010_2/2025-10-10_11-15-28_NM10_FirstSolo.json 251010_2/2025-10-10_11-48-28_NM10_SecondSolo.json
251010_3/2025-10-10_14-28-00_HT10_FirstSolo.json 251010_3/2025-10-10_15-00-24_HT10_SecondSolo.json
251010_3/2025-10-10_14-27-52_WT10_FirstSolo.json 251010_3/2025-10-10_15-00-35_WT10_SecondSolo.json
251010_4/2025-10-10_15-28-22_YL10_FirstSolo.json 251010_4/2025-10-10_15-58-20_YL10_SecondSolo.json
251010_4/2025-10-10_15-28-37_NO10_FirstSolo.json 251010_4/2025-10-10_15-58-29_NO10_SecondSolo.json
251013_1/2025-10-13_13-13-04_FA13_FirstSolo.json 251013_1/2025-10-13_13-44-03_FA13_SecondSolo.json
251013_1/2025-10-13_13-12-53_HW13_FirstSolo.json 251013_1/2025-10-13_13-44-12_HW13_SecondSolo.json
251013_2/2025-10-13_14-16-45_SW13_FirstSolo.json 251013_2/2025-10-13_14-45-48_SW13_SecondSolo.json
251013_2/2025-10-13_14-16-36_MU13_FirstSolo.json 251013_2/2025-10-13_14-45-03_MU13_SecondSolo.json
251015_1/2025-10-15_09-10-38_CS15_FirstSolo.json 251015_1/2025-10-15_09-42-32_CS15_SecondSolo.json
251015_1/2025-10-15_09-10-52_SK15_FirstSolo.json 251015_1/2025-10-15_09-42-45_SK15_SecondSolo.json
251017_1/2025-10-17_10-16-46_XL17_FirstSolo.json 251017_1/2025-10-17_10-51-05_XL17_SecondSolo.json
251017_1/2025-10-17_10-17-01_EV17_FirstSolo.json 251017_1/2025-10-17_10-50-57_EV17_SecondSolo.json
251017_2/2025-10-17_11-18-32_MZ17_FirstSolo.json 251017_2/2025-10-17_11-50-05_MZ17_SecondSolo.json
251017_2/2025-10-17_11-18-44_CW17_FirstSolo.json 251017_2/2025-10-17_11-50-15_CW17_SecondSolo.json
251103_1/2025-11-03_13-18-16_TG03_FirstSolo.json 251103_1/2025-11-03_13-51-23_TG03_SecondSolo.json
251103_1/2025-11-03_13-17-59_HW03_FirstSolo.json 251103_1/2025-11-03_13-51-34_HW03_SecondSolo.json
251103_2/2025-11-03_16-13-23_YG03_FirstSolo.json 251103_2/2025-11-03_16-47-32_YG03_SecondSolo.json
251103_2/2025-11-03_16-13-02_XA03_FirstSolo.json 251103_2/2025-11-03_16-47-45_XA03_SecondSolo.json
251104_1/2025-11-04_13-18-40_UL04_FirstSolo.json 251104_1/2025-11-04_13-49-59_UL04_SecondSolo.json
251104_1/2025-11-04_13-18-58_MV04_FirstSolo.json 251104_1/2025-11-04_13-50-13_MV04_SecondSolo.json
251105_1/2025-11-05_14-16-53_ZO05_FirstSolo.json 251105_1/2025-11-05_14-52-43_ZO05_SecondSolo.json
251105_1/2025-11-05_14-16-20_CL05_FirstSolo.json 251105_1/2025-11-05_14-52-33_CL05_SecondSolo.json
251120_1/2025-11-20_10-21-38_NH20_FirstSolo.json 251120_1/2025-11-20_10-57-11_NH20_SecondSolo.json
251120_1/2025-11-20_10-21-21_MA20_FirstSolo.json 251120_1/2025-11-20_10-56-50_MA20_SecondSolo.json
251215_1/2025-12-15_11-22-45_CK15_FirstSolo.json 251215_1/2025-12-15_11-56-34_CK15_SecondSolo.json
251215_1/2025-12-15_11-23-02_AM15_FirstSolo.json 251215_1/2025-12-15_11-56-13_AM15_SecondSolo.json
251219_1/2025-12-19_12-55-14_PE19_FirstSolo.json 251219_1/2025-12-19_13-28-00_PE19_SecondSolo.json
251219_1/2025-12-19_12-54-54_AT19_FirstSolo.json 251219_1/2025-12-19_13-27-38_AT19_SecondSolo.json
251219_2/2025-12-19_13-53-59_NJ19_FirstSolo.json 251219_2/2025-12-19_14-42-48_NJ19_SecondSolo.json
251219_2/2025-12-19_13-54-13_BL19_FirstSolo.json 251219_2/2025-12-19_14-31-09_BL19_SecondSolo.json
260107_1/2026-01-07_10-17-45_AF07_FirstSolo.json 260107_1/2026-01-07_10-50-50_AF07_SecondSolo.json
260107_1/2026-01-07_10-17-37_AC07_FirstSolo.json 260107_1/2026-01-07_10-50-33_AC07_SecondSolo.json
260109_1/2026-01-09_10-17-52_DM09_FirstSolo.json 260109_1/2026-01-09_10-52-05_DM09_SecondSolo.json
260109_1/2026-01-09_10-18-05_FB09_FirstSolo.json 260109_1/2026-01-09_10-51-37_FB09_SecondSolo.json
260109_2/2026-01-09_11-20-42_IM09_FirstSolo.json 260109_2/2026-01-09_11-51-57_IM09_SecondSolo.json
260109_2/2026-01-09_11-20-34_KM09_FirstSolo.json 260109_2/2026-01-09_11-52-09_KM09_SecondSolo.json
260114_1/2026-01-14_13-42-41_CG14_FirstSolo.json 260114_1/2026-01-14_14-17-07_CG14_SecondSolo.json
260114_1/2026-01-14_13-43-11_JD14_FirstSolo.json 260114_1/2026-01-14_14-17-15_JD14_SecondSolo.json
260116_1/2026-01-16_14-19-35_EL16_FirstSolo.json 260116_1/2026-01-16_14-54-53_EL16_SecondSolo.json
260116_1/2026-01-16_14-20-00_FR16_FirstSolo.json 260116_1/2026-01-16_14-54-10_FR16_SecondSolo.json
260120_1/2026-01-20_12-21-29_RA20_FirstSolo.json 260120_1/2026-01-20_12-51-59_RA20_SecondSolo.json
260120_1/2026-01-20_12-21-42_AM20_FirstSolo.json 260120_1/2026-01-20_12-51-36_AM20_SecondSolo.json
260120_2/2026-01-20_13-24-01_LW20_FirstSolo.json 260120_2/2026-01-20_13-59-22_LW20_SecondSolo.json
260120_2/2026-01-20_13-24-10_SG20_FirstSolo.json 260120_2/2026-01-20_13-59-04_SG20_SecondSolo.json
260120_3/2026-01-20_14-26-50_HH20_FirstSolo.json 260120_3/2026-01-20_14-53-08_HH20_SecondSolo.json
260120_3/2026-01-20_14-26-59_KH20_FirstSolo.json 260120_3/2026-01-20_14-52-58_KH20_SecondSolo.json
260121_1/2026-01-21_13-14-42_ZC21_FirstSolo.json 260121_1/2026-01-21_13-45-59_ZC21_SecondSolo.json
260121_1/2026-01-21_13-14-57_JX21_FirstSolo.json 260121_1/2026-01-21_13-45-36_JX21_SecondSolo.json
260128_1/2026-01-28_12-23-38_OK28_FirstSolo.json 260128_1/2026-01-28_13-00-55_OK28_SecondSolo.json
260128_1/2026-01-28_12-25-47_DP28_FirstSolo.json 260128_1/2026-01-28_13-01-03_DP28_SecondSolo.json
260128_2/2026-01-28_13-26-00_YG28_FirstSolo.json 260128_2/2026-01-28_13-57-09_YG28_SecondSolo.json
260128_2/2026-01-28_13-25-50_GN28_FirstSolo.json 260128_2/2026-01-28_13-57-19_GN28_SecondSolo.json
260130_1/2026-01-30_17-16-35_ZT30_FirstSolo.json 260130_1/2026-01-30_17-50-06_ZT30_SecondSolo.json
260130_1/2026-01-30_17-16-07_SW30_FirstSolo.json 260130_1/2026-01-30_17-50-26_SW30_SecondSolo.json
260202_1/2026-02-02_13-10-03_KF02_FirstSolo.json 260202_1/2026-02-02_13-48-43_KF02_SecondSolo.json
260202_1/2026-02-02_13-10-26_KE02_FirstSolo.json 260202_1/2026-02-02_13-48-33_KE02_SecondSolo.json
260204_1/2026-02-04_13-21-13_YL04_FirstSolo.json 260204_1/2026-02-04_13-57-58_YL04_SecondSolo.json
260204_1/2026-02-04_13-21-43_LY04_FirstSolo.json 260204_1/2026-02-04_13-57-43_LY04_SecondSolo.json
260205_1/2026-02-05_13-17-46_MO05_FirstSolo.json 260205_1/2026-02-05_13-50-52_MO05_SecondSolo.json
260205_1/2026-02-05_13-18-03_IP05_FirstSolo.json 260205_1/2026-02-05_13-50-39_IP05_SecondSolo.json
260209_1/2026-02-09_17-09-55_KW09_FirstSolo.json 260209_1/2026-02-09_17-43-11_KW09_SecondSolo.json
260209_1/2026-02-09_17-09-44_BR09_FirstSolo.json 260209_1/2026-02-09_17-43-03_BR09_SecondSolo.json
260209_2/2026-02-09_18-13-23_YS09_FirstSolo.json 260209_2/2026-02-09_18-45-06_YS09_SecondSolo.json
260209_2/2026-02-09_18-13-33_ZX09_FirstSolo.json 260209_2/2026-02-09_18-44-58_ZX09_SecondSolo.json
260213_1/2026-02-13_13-11-07_NA13_FirstSolo.json 260213_1/2026-02-13_13-42-18_NA13_SecondSolo.json
260213_1/2026-02-13_13-11-17_EK13_FirstSolo.json 260213_1/2026-02-13_13-42-34_EK13_SecondSolo.json
260216_1/2026-02-16_09-20-00_MP16_FirstSolo.json 260216_1/2026-02-16_09-52-24_MP16_SecondSolo.json
260216_1/2026-02-16_09-19-49_JS16_FirstSolo.json 260216_1/2026-02-16_09-52-33_JS16_SecondSolo.json
260218_1/2026-02-18_17-14-24_AJ18_FirstSolo.json 260218_1/2026-02-18_17-42-50_AJ18_SecondSolo.json
260218_1/2026-02-18_17-14-38_LZ18_FirstSolo.json 260218_1/2026-02-18_17-42-42_LZ18_SecondSolo.json
260219_1/2026-02-19_14-40-33_NB19_FirstSolo.json 260219_1/2026-02-19_15-12-07_NB19_SecondSolo.json
260219_1/2026-02-19_14-40-21_AS19_FirstSolo.json 260219_1/2026-02-19_15-11-56_AS19_SecondSolo.json
260220_1/2026-02-20_11-15-38_SS20_FirstSolo.json 260220_1/2026-02-20_11-46-47_SS20_SecondSolo.json
260220_1/2026-02-20_11-15-49_YL20_FirstSolo.json 260220_1/2026-02-20_11-46-38_YL20_SecondSolo.json
260220_2/2026-02-20_16-16-43_KR20_FirstSolo.json 260220_2/2026-02-20_16-47-26_KR20_SecondSolo.json
260220_2/2026-02-20_16-16-30_PJ20_FirstSolo.json 260220_2/2026-02-20_16-47-16_PJ20_SecondSolo.json
260304_1/2026-03-04_13-08-35_RL04_FirstSolo.json 260304_1/2026-03-04_13-41-59_RL04_SecondSolo.json
260304_1/2026-03-04_13-08-23_AK04_FirstSolo.json 260304_1/2026-03-04_13-41-49_AK04_SecondSolo.json
260306_1/2026-03-06_13-25-07_AT06_FirstSolo.json 260306_1/2026-03-06_13-57-24_AT06_SecondSolo.json
260306_1/2026-03-06_13-25-17_AK06_FirstSolo.json 260306_1/2026-03-06_13-57-39_AK06_SecondSolo.json
260306_2/2026-03-06_15-10-39_ZB06_FirstSolo.json 260306_2/2026-03-06_15-42-15_ZB06_SecondSolo.json
260306_2/2026-03-06_15-10-49_LS06_FirstSolo.json 260306_2/2026-03-06_15-42-04_LS06_SecondSolo.json
260309_1/2026-03-09_14-17-01_NC09_FirstSolo.json 260309_1/2026-03-09_14-50-07_NC09_SecondSolo.json
260309_1/2026-03-09_14-17-17_EE09_FirstSolo.json 260309_1/2026-03-09_14-50-00_EE09_SecondSolo.json
260317_1/2026-03-17_15-13-52_AS17_FirstSolo.json 260317_1/2026-03-17_15-49-57_AS17_SecondSolo.json
260317_1/2026-03-17_15-14-05_QC17_FirstSolo.json 260317_1/2026-03-17_15-50-06_QC17_SecondSolo.json
260319_1/2026-03-19_11-48-04_JP19_FirstSolo.json 260319_1/2026-03-19_12-20-55_JP19_SecondSolo.json
260319_1/2026-03-19_11-47-54_LM19_FirstSolo.json 260319_1/2026-03-19_12-20-31_LM19_SecondSolo.json
260323_1/2026-03-23_11-17-48_SL23_FirstSolo.json 260323_1/2026-03-23_11-50-58_SL23_SecondSolo.json
260323_1/2026-03-23_11-17-37_KF23_FirstSolo.json 260323_1/2026-03-23_11-51-09_KF23_SecondSolo.json
260327_1/2026-03-27_11-09-47_MI27_FirstSolo.json 260327_1/2026-03-27_11-45-24_MI27_SecondSolo.json
260327_1/2026-03-27_11-09-34_YZ27_FirstSolo.json 260327_1/2026-03-27_11-45-34_YZ27_SecondSolo.json
260327_2/2026-03-27_14-15-06_DT27_FirstSolo.json 260327_2/2026-03-27_14-46-29_DT27_SecondSolo.json
260327_2/2026-03-27_14-15-19_RW27_FirstSolo.json 260327_2/2026-03-27_14-46-43_RW27_SecondSolo.json
260330_1/2026-03-30_15-21-31_JJ30_FirstSolo.json 260330_1/2026-03-30_15-52-24_JJ30_SecondSolo.json
260330_1/2026-03-30_15-21-21_NC30_FirstSolo.json 260330_1/2026-03-30_15-52-16_NC30_SecondSolo.json

# Questionnaire scores dataframe

In [90]:
AQ_path='/Users/benny/Desktop/questionnaire_responses/AQ.csv'
BIS_path='/Users/benny/Desktop/questionnaire_responses/BIS.csv'
GAD_path='/Users/benny/Desktop/questionnaire_responses/GAD.csv'

In [91]:
questionnaire_data_df = prepare_questionnaire_data.preprocess_data(AQ_path, GAD_path, BIS_path)

/Users/benny/Desktop/questionnaire_responses/AQ.csv
/Users/benny/Desktop/questionnaire_responses/GAD.csv
/Users/benny/Desktop/questionnaire_responses/BIS.csv

In [92]:
items_df = prepare_questionnaire_data.process_items_pseudo(AQ_path, GAD_path, BIS_path)

/Users/benny/Desktop/questionnaire_responses/AQ.csv
/Users/benny/Desktop/questionnaire_responses/GAD.csv
/Users/benny/Desktop/questionnaire_responses/BIS.csv
/Users/benny/Desktop/questionnaire_responses/AQ.csv
/Users/benny/Desktop/questionnaire_responses/GAD.csv
/Users/benny/Desktop/questionnaire_responses/BIS.csv

In [93]:
items_df

    pseudonym       date  GAD1  GAD2  GAD3  GAD4  GAD5  GAD6  GAD7  AQ1  AQ2  AQ3  AQ4  AQ5  AQ6  AQ7  AQ8  AQ9  AQ10  BIS1  BIS2  BIS3  BIS4  BIS5  BIS6  BIS7  BIS8  GAD_total  AQ_total  BIS_total
0        AK06 2026-03-06     4     4     4     4     2     2     2    3    1    1    1    1    3    2    4    4     1     2     3     3     3     2     4     1     3         15         6         21
1        AJ18 2026-02-18     3     2     2     2     1     2     2    2    1    3    3    4    4    4    3    3     4     1     1     3     2     2     2     2     1          7         2         14
2        AW17 2024-10-17     2     2     1     1     1     3     2    1    1    2    2    2    2    1    4    2     1     1     2     1     2     2     1     1     1          5         9         11
3        AT19 2025-12-19     2     2     2     1     2     2     1    1    3    3    3    4    3    4    2    3     4     1     1     2     2     2     3     1     2          5         2         14
4        AE14 2025-03-14     2     1     2     1     1     2     1    2    4    3    4    3    4    4    3    3     2     3     2     2     2     2     2     2     2          3         2         17
..        ...        ...   ...   ...   ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...        ...       ...        ...
189      ZT30 2026-01-30     2     2     2     2     2     2     3    4    3    4    1    3    4    3    2    4     3     3     3     3     4     3     3     1     2          8         2         22
190      ZZ30 2025-05-30     1     1     2     2     1     1     1    2    1    1    1    1    3    1    2    3     2     1     1     1     2     2     3     1     2          2         8         13
191      ZC21 2026-01-21     2     3     3     2     1     2     2    2    1    4    1    4    4    4    4    4     3     2     3     2     2     2     2     2     2          8         3         17
192      ZH17 2025-10-17     2     2     2     2     1     1     2    1    2    3    2    2    2    1    2    2     1     3     4     2     2     3     2     3     2          5         9         21
193      ZS20 2024-11-20     1     2     1     1     1     1     2    2    1    3    1    3    4    4    1    3     4     3     2     2     2     2     2     2     2          2         4         17

[194 rows x 30 columns]

In [94]:
questionnaire_data_df

          date pseudonym  GAD_total  AQ_total  BIS_total
0   2026-03-06      AK06         15         6         21
3   2026-02-18      AJ18          7         2         14
4   2024-10-17      AW17          5         9         11
6   2025-12-19      AT19          5         2         14
8   2025-03-14      AE14          3         2         17
..         ...       ...        ...       ...        ...
280 2026-01-30      ZT30          8         2         22
281 2025-05-30      ZZ30          2         8         13
282 2026-01-21      ZC21          8         3         17
283 2025-10-17      ZH17          5         9         21
284 2024-11-20      ZS20          2         4         17

[194 rows x 5 columns]

### Pseudonym lists

In [95]:
import re
pseudo_tuples_list = []
experiment_dates_socials = []
for file in social_files:
     # match the session number and the pseudonym string
    match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?_.*?)_Social\.json', file)
    if not match:
        print(f"Filename does not match expected pattern: {file}")
    if match:
        session, date, time, pseudonyms = match.groups()
        pseudo_tuples = pseudonyms.split('_')[0::]
        pseudo_tuples_list.append(pseudo_tuples)
        experiment_dates_socials.append(date)

In [96]:
first_solo_pseudo_list = []
second_solo_pseudo_list = []
first_solo_dates = []
second_solo_dates = []
solo_dates = {}


for first_solo, second_solo in zip(first_solos, second_solos):
   # match the session number and the pseudonym string
    first_match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?)_FirstSolo\.json', first_solo)
    second_match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?)_SecondSolo\.json', second_solo)

    if not first_match:
        print(f"Filename does not match expected pattern: {first_solo}")
    if first_match:
        session, date, time, pseudonyms = first_match.groups()
        first_pseudo = pseudonyms.split('_')[0::]
        first_solo_pseudo_list.append(first_pseudo)
        first_solo_dates.append(date)

    if not second_match:
        print(f"Filename does not match expected pattern: {second_solo}")
    if second_match:
        session, date, time, pseudonyms = second_match.groups()
        second_pseudo = pseudonyms.split('_')[0::]
        second_solo_pseudo_list.append(second_pseudo)
        second_solo_dates.append(date)

for i, pseudonym in enumerate(first_solo_pseudo_list):
    player = pseudonym[0]
    if player not in solo_dates:
        solo_dates[player] = []
    solo_dates[player] = first_solo_dates[i]

In [97]:
len(first_solo_pseudo_list)

202

In [98]:
ordered_solo_pseudo_list = []

for first_solo in (ordered_solos):
   # match the session number and the pseudonym string
    first_match = re.search(r'(\d+_\d)[/\\](\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_(.*?)_FirstSolo\.json', first_solo)

    if first_match:
        session, date, time, pseudonyms = first_match.groups()
        first_pseudo = pseudonyms.split('_')[0::]
        ordered_solo_pseudo_list.append(first_pseudo)

### Match player to opponent

In [99]:
opponent_dict = {}

for i, pseudonym in enumerate(pseudo_tuples_list):
    player0 = pseudonym[0]
    player1 = pseudonym[1]

    if player0 not in opponent_dict:
        opponent_dict[player0] = []
    if player1 not in opponent_dict:
        opponent_dict[player1] = []

    opponent_dict[player0] = player1
    opponent_dict[player1] = player0

In [100]:
questionnaire_data_df.set_index('pseudonym', inplace=True)

In [101]:
df = questionnaire_data_df

In [102]:
for pseudonym in df.index:
    if pseudonym in opponent_dict:
        df.loc[pseudonym, 'opponent'] = opponent_dict[pseudonym]

In [103]:
df

                date  GAD_total  AQ_total  BIS_total opponent
pseudonym
AK06      2026-03-06         15         6         21     AT06
AJ18      2026-02-18          7         2         14     LZ18
AW17      2024-10-17          5         9         11     SP17
AT19      2025-12-19          5         2         14     PE19
AE14      2025-03-14          3         2         17     JL14
...              ...        ...       ...        ...      ...
ZT30      2026-01-30          8         2         22     SW30
ZZ30      2025-05-30          2         8         13     VW30
ZC21      2026-01-21          8         3         17     JX21
ZH17      2025-10-17          5         9         21     EM17
ZS20      2024-11-20          2         4         17     VC20

[194 rows x 5 columns]

# Proportion scores and wins

In [104]:
import analysis.player_scores as player_scores

In [105]:
proportion_scores_all_sessions = player_scores.proportion_score_sessions_df(social_lists)
proportion_wins_all_sessions = player_scores.proportion_wins_sessions(social_lists)

In [106]:
proportion_scores = {}
proportion_wins = {}

In [107]:
len(proportion_scores_all_sessions), len(pseudo_tuples_list)

(101, 101)

In [108]:
from collections import defaultdict, Counter

In [109]:
proportion_scores = defaultdict(list)
proportion_wins = defaultdict(list)

for i, pair in enumerate(pseudo_tuples_list):
    player0, player1 = pair

    proportion_scores[player0].append(proportion_scores_all_sessions[i][0])
    proportion_wins[player0].append(proportion_wins_all_sessions[i][0])

    proportion_scores[player1].append(proportion_scores_all_sessions[i][1])
    proportion_wins[player1].append(proportion_wins_all_sessions[i][1])

In [110]:
len(proportion_scores)

202

Check for repeated or missing pseudonyms

In [111]:
from collections import defaultdict

# Store filenames associated with each pseudonym
pseudonym_to_files = defaultdict(list)

for i, pair in enumerate(pseudo_tuples_list):

    filename = social_files[i]   # parallel list of filenames
    player0, player1 = pair

    pseudonym_to_files[player0].append(filename)
    pseudonym_to_files[player1].append(filename)

# Find repeated pseudonyms
print("Repeated pseudonyms and their filenames:\n")

for pseudonym, files in pseudonym_to_files.items():

    if len(files) > 1:
        print(f"{pseudonym}:")
        
        for f in files:
            print(f"   {f}")
        
        print()

Repeated pseudonyms and their filenames:

In [112]:
all_pseudonyms_in_sessions = [
    player
    for pair in pseudo_tuples_list
    for player in pair
]

counts = Counter(all_pseudonyms_in_sessions)

print("Total player appearances:", len(all_pseudonyms_in_sessions))
print("Unique pseudonyms:", len(counts))
print("Dictionary entries:", len(proportion_scores))

print("\nRepeated pseudonyms:")
for pseudonym, count in counts.items():
    if count > 1:
        print(pseudonym, count)

Total player appearances: 202
Unique pseudonyms: 202
Dictionary entries: 202

Repeated pseudonyms:

In [113]:
len(proportion_wins)

202

In [115]:
for pseudonym in df.index:
    df.loc[pseudonym, 'proportion_score'] = proportion_scores.get(pseudonym, np.nan)
    df.loc[pseudonym, 'proportion_wins'] = proportion_wins.get(pseudonym, np.nan)

In [116]:
df

                date  GAD_total  AQ_total  BIS_total opponent  proportion_score  proportion_wins
pseudonym
AK06      2026-03-06         15         6         21     AT06       0.490598291      0.528985507
AJ18      2026-02-18          7         2         14     LZ18       0.249443207      0.266055046
AW17      2024-10-17          5         9         11     SP17       0.579908676      0.603603604
AT19      2025-12-19          5         2         14     PE19       0.465573770      0.445255474
AE14      2025-03-14          3         2         17     JL14       0.356363636      0.381679389
...              ...        ...       ...        ...      ...               ...              ...
ZT30      2026-01-30          8         2         22     SW30               NaN      0.963768116
ZZ30      2025-05-30          2         8         13     VW30       0.401337793      0.402684564
ZC21      2026-01-21          8         3         17     JX21       0.550847458      0.500000000
ZH17      2025-10-17          5         9         21     EM17       0.335674157      0.346590909
ZS20      2024-11-20          2         4         17     VC20       0.296041308      0.330985915

[194 rows x 7 columns]

# Scores per unit time

## Social

In [117]:
# trial logic
scores_per_unit_time = [(0, 0) for _ in range(len(social_lists))]
delta_times_list = []
for trial_list_index in range(len(social_lists)):
    # define trial
    trial_list = social_lists[trial_list_index]
    delta_times = []
    for trial_index in range(len(trial_list)):
        trial = trial_list[trial_index]
        # cut trials to only return timepoints between slice onset and server-selected trigger activation
        slice_onset = trial[trial['eventDescription'] == globals.SLICE_ONSET]
        slice_onset_index = slice_onset.index[0] - trial.index[0]
        selected_trigger_activation = trial[trial['eventDescription'] == globals.SELECTED_TRIGGER_ACTIVATION]
        selected_trigger_activation_index = selected_trigger_activation.index[0] - trial.index[0]

        # extract application time between slice onset and server-selected trigger activation
        time_app_onset = trial['timeApplication'].iloc[slice_onset_index]
        time_app_trigger = trial['timeApplication'].iloc[selected_trigger_activation_index]        
        time = time_app_trigger - time_app_onset
        delta_time = time.total_seconds()
        delta_times.append(delta_time)
        
    total_time = sum(delta_times)
    delta_times_list.append(total_time)

    # access final trial event log event for the final player scores
    final_trial = trial_list[-1]
    final_trial_trial_end = final_trial[final_trial['eventDescription'] == 'trial end']
    
    # flexibly index player scores
    player0_score = final_trial_trial_end[globals.PLAYER_SCORE_DICT[0]['score']].item()
    player1_score = final_trial_trial_end[globals.PLAYER_SCORE_DICT[1]['score']].item()

    # score per unit time as final score divided by total time spent playing (active trials)
    score_per_time_unit_p0 = player0_score/total_time
    score_per_time_unit_p1 = player1_score/total_time
    print(player0_score, player1_score)
    print(score_per_time_unit_p0, score_per_time_unit_p1)
    scores_per_unit_time[trial_list_index] = (score_per_time_unit_p0, score_per_time_unit_p1)

2150.0 2920.0
6.506909429873675 8.837290946619131
1520.0 2540.0
5.045425425624787 8.43117143492563
1840.0 2540.0
5.407391080743516 7.464550731026376
2390.0 4730.0
5.012047788512554 9.919241020780076
1460.0 2420.0
4.0854588445986595 6.771787947896408
3700.0 960.0
10.612635920617482 2.753548779403455
2320.0 2390.0
8.171977865211678 8.418546162868928
2050.0 3270.0
5.979622612890899 9.53822728983085
1420.0 2920.0
4.622952634269101 9.506353304271673
3850.0 1050.0
7.373176575130754 2.010866338672024
1540.0 4640.0
3.899691823055282 11.749720817517213
1720.0 4090.0
4.177200741210271 9.932994785784889
3010.0 1110.0
10.760837700827262 3.968282341501083
2930.0 2140.0
7.970685288508884 5.821592668057683
2400.0 2870.0
7.421104384017415 8.874403992554159
3020.0 2650.0
9.76489874576019 8.568536978895532
2770.0 2980.0
7.703324665934342 8.287331229055717
2780.0 1690.0
8.557664188638007 5.202321035538932
2030.0 3700.0
5.553245502691819 10.121678995054054
1380.0 4190.0
3.7283391599889772 11.320102232140446
2780.0 2600.0
7.640280216896013 7.145585814363177
450.0 3890.0
0.6970540944957511 6.025645394641049
1960.0 3540.0
5.186872977185698 9.368127724100699
1880.0 2770.0
4.183141494761061 6.163458478983052
1900.0 3630.0
5.574512156837433 10.650252173326253
2110.0 3320.0
6.667909657724505 10.491687233955146
990.0 3960.0
2.1401379632371857 8.560551852948743
2420.0 3060.0
8.072855856156387 10.207825999933283
3670.0 1870.0
10.914141098729855 5.561156363657991
2480.0 3100.0
8.887519127876349 11.109398909845435
4350.0 1060.0
12.210629142140144 2.9754636530272536
2660.0 3080.0
8.332132587409083 9.64773246963157
3030.0 2450.0
9.100219546550777 7.358263329719275
4700.0 1370.0
11.955849844701142 3.4850030398384177
2000.0 3300.0
6.8224923929209815 11.257112448319619
3830.0 2690.0
10.139517644878616 7.121488894183676
1510.0 3480.0
4.137496403666206 9.535422175336686
2000.0 3030.0
6.079249091152261 9.210062373095676
3160.0 2690.0
9.57735380139114 8.152873963842458
2120.0 3440.0
5.5773035315906885 9.049964221071683
2380.0 3100.0
7.546260479155834 9.82916280898449
2630.0 2400.0
8.104901462272146 7.39610779827116
3450.0 1470.0
9.825700615174298 4.186602870813397
2780.0 2640.0
8.272160015711153 7.855576417797641
2490.0 2610.0
9.17603617348236 9.618254784252596
3300.0 1780.0
8.224832014037046 4.436424540904832
2730.0 3260.0
6.903230863763601 8.24341854061148
2400.0 3580.0
6.676533098912838 9.959161872544982
3670.0 2190.0
11.787301832010073 7.033839512834349
2590.0 2610.0
7.36699585855368 7.42388385746143
2600.0 3110.0
7.31458922954869 8.749374039960163
3180.0 2220.0
9.330876398164342 6.514008051548691
3650.0 2310.0
10.050500322166723 6.360727601152091
1730.0 3560.0
4.2864859239731015 8.820745600777018
2510.0 3030.0
8.108256531022965 9.788054696812583
3340.0 2080.0
9.616575059671712 5.988765306621905
1920.0 nan
9.422665436485346 nan
3340.0 2190.0
10.095850121966333 6.619734062007865
4490.0 1240.0
14.037259701809838 3.8766596949318926
3240.0 2130.0
10.584257550267056 6.958169315453342
2770.0 2800.0
7.992405771844226 8.078966123163838
2850.0 2490.0
7.560062708730679 6.605107419206804
1570.0 3650.0
5.033567805685046 11.702243624681795
3680.0 1900.0
10.525713631943253 5.434471712144614
4570.0 1380.0
14.118097733072185 4.263233013487881
630.0 4570.0
1.8916192260575053 13.72174581441714
3260.0 2840.0
9.324196002608486 8.122919216996351
3240.0 2210.0
9.938101577213528 6.778766816556142
3120.0 2430.0
9.892670862596509 7.704868652599204
2630.0 2510.0
8.526807569730156 8.137751711035245
2480.0 nan
8.486437099417927 nan
1790.0 2500.0
6.714128176082701 9.377273988942319
2530.0 2840.0
7.769530542239528 8.721528355715519
2860.0 2000.0
9.697972581186612 6.781799007822806
1890.0 2120.0
6.607282693813626 7.411343550732744
2550.0 1490.0
10.931679148786584 6.387530169290984
2600.0 2120.0
9.782710939704637 7.976671996989936
1800.0 4100.0
5.119177291329535 11.660348274695053
2970.0 2420.0
10.479332427712011 8.538715311469046
6020.0 nan
16.684496721302388 nan
2850.0 2620.0
7.518717649728008 6.911943944662238
2590.0 3350.0
7.161640153850834 9.263125295521348
1770.0 3940.0
5.580990578531159 12.423221965769924
2760.0 2800.0
9.370766603402675 9.506574815046191
2590.0 2600.0
8.0522807541163 8.083370641197831
2800.0 nan
8.481995450015297 nan
1150.0 4580.0
3.1984336019090476 12.738109475429077
1120.0 3370.0
3.7596635101158444 11.312558954544997
2650.0 2540.0
8.988139048206952 8.615046483941757
1900.0 2870.0
6.324310650139135 9.5530376662628
3260.0 1500.0
8.453918365230018 3.8898397386027694
4000.0 1490.0
12.253475391958045 4.564419583504372
2980.0 2870.0
8.845932355333385 8.519404650941885
2790.0 2400.0
9.32168846182117 8.018656741351544
3740.0 1740.0
11.027536407087108 5.1304581145271575
2210.0 2900.0
7.036558263339213 9.233492743748288
1730.0 3460.0
5.328602273742311 10.657204547484621
1970.0 3260.0
6.468900024299422 10.70488024325691
3300.0 2390.0
10.743446497636443 7.780859736166999
2320.0 1790.0
8.919303371650456 6.88170389450617
2770.0 2480.0
9.047054481558053 8.099889932947281

In [118]:
scores_per_unit_time_dict = {}

for i, tuple in enumerate(pseudo_tuples_list):
    player0 = tuple[0]
    player1 = tuple[1]

    if player0 not in scores_per_unit_time_dict:
        scores_per_unit_time_dict[player0] = []
    if player1 not in scores_per_unit_time_dict:
        scores_per_unit_time_dict[player1] = []
    
    scores_per_unit_time_dict[player0] = scores_per_unit_time[i][0]
    scores_per_unit_time_dict[player1] = scores_per_unit_time[i][1]

In [119]:
len(scores_per_unit_time_dict)

202

In [127]:
for pseudonym in df.index:
    df.loc[pseudonym, 'scores_per_unit_time_socials'] = scores_per_unit_time_dict.get(pseudonym, np.nan)

## Solo

In [123]:
# trial logic
scores_per_unit_time_comb_solos = [0 for _ in range(len(combined_solos))]
delta_times_list_comb_solos = []
for trial_list_index in range(len(combined_solos)):
    # define trial
    trial_list = combined_solos[trial_list_index]
    delta_times = []
    for trial_index in range(len(trial_list)):
        trial = trial_list[trial_index]
        # cut trials to only return timepoints between slice onset and server-selected trigger activation
        slice_onset = trial[trial['eventDescription'] == globals.SLICE_ONSET]
        slice_onset_index = slice_onset.index[0] - trial.index[0]
        #selected_trigger_activation = trial[trial['eventDescription'] == globals.SELECTED_TRIGGER_ACTIVATION]

        selected_trigger_activation = trial[
            trial['eventDescription'].astype(str).str.strip()
            == str(globals.SELECTED_TRIGGER_ACTIVATION).strip()
        ]

        if selected_trigger_activation.empty:
            print(trial_list_index, trial_index)
            print("Skipping trial: no selected trigger activation found")
            continue

        selected_trigger_activation_index = selected_trigger_activation.index[0] - trial.index[0]

        # extract application time between slice onset and server-selected trigger activation
        time_app_onset = trial['timeApplication'].iloc[slice_onset_index]
        time_app_trigger = trial['timeApplication'].iloc[selected_trigger_activation_index]        
        time = time_app_trigger - time_app_onset
        delta_time = time.total_seconds()
        delta_times.append(delta_time)
        
    total_time = sum(delta_times)
    delta_times_list.append(total_time)

    # access final trial event log event for the final player scores
    final_trial = trial_list[-1]
    final_trial_trial_end = final_trial[final_trial['eventDescription'] == 'trial end']
    
    # flexibly index player scores
    player0_score = final_trial_trial_end[globals.PLAYER_SCORE_DICT[0]['score']].item()
    # score per unit time as final score divided by total time spent playing (active trials)
    score_per_time_unit_p0 = player0_score/total_time

    scores_per_unit_time_comb_solos[trial_list_index] = score_per_time_unit_p0

145 75
Skipping trial: no selected trigger activation found

In [124]:
scores_per_unit_time_dict_comb_solos = {}

for i, pseudonym in enumerate(ordered_solo_pseudo_list):
    player = pseudonym[0]

    if player not in scores_per_unit_time_dict_comb_solos:
        scores_per_unit_time_dict_comb_solos[player] = []
    
    scores_per_unit_time_dict_comb_solos[player] = scores_per_unit_time_comb_solos[i]

In [125]:
len(scores_per_unit_time_dict_comb_solos)

202

In [126]:
for pseudonym in df.index:
    df.loc[pseudonym, 'scores_per_unit_time_solos'] = scores_per_unit_time_dict_comb_solos.get(pseudonym, np.nan)